// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/big_button_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BigButtonInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PressType     PressType              `protobuf:"varint,1,opt,name=press_type,json=pressType,proto3,enum=common.PressType" json:"press_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BigButtonInput) Reset() {
	*x = BigButtonInput{}
	mi := &file_proto_big_button_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BigButtonInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BigButtonInput) ProtoMessage() {}

func (x *BigButtonInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_big_button_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BigButtonInput.ProtoReflect.Descriptor instead.
func (*BigButtonInput) Descriptor() ([]byte, []int) {
	return file_proto_big_button_module_proto_rawDescGZIP(), []int{0}
}

func (x *BigButtonInput) GetPressType() PressType {
	if x != nil {
		return x.PressType
	}
	return PressType_TAP
}

var File_proto_big_button_module_proto protoreflect.FileDescriptor

const file_proto_big_button_module_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/big_button_module.proto\x12\amodules\x1a\x12proto/common.proto\"B\n" +
	"\x0eBigButtonInput\x120\n" +
	"\n" +
	"press_type\x18\x01 \x01(\x0e2\x11.common.PressTypeR\tpressTypeB\tZ\a./protob\x06proto3"

var (
	file_proto_big_button_module_proto_rawDescOnce sync.Once
	file_proto_big_button_module_proto_rawDescData []byte
)

func file_proto_big_button_module_proto_rawDescGZIP() []byte {
	file_proto_big_button_module_proto_rawDescOnce.Do(func() {
		file_proto_big_button_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_big_button_module_proto_rawDesc), len(file_proto_big_button_module_proto_rawDesc)))
	})
	return file_proto_big_button_module_proto_rawDescData
}

var file_proto_big_button_module_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_big_button_module_proto_goTypes = []any{
	(*BigButtonInput)(nil), // 0: modules.BigButtonInput
	(PressType)(0),         // 1: common.PressType
}
var file_proto_big_button_module_proto_depIdxs = []int32{
	1, // 0: modules.BigButtonInput.press_type:type_name -> common.PressType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_big_button_module_proto_init() }
func file_proto_big_button_module_proto_init() {
	if File_proto_big_button_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_big_button_module_proto_rawDesc), len(file_proto_big_button_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_big_button_module_proto_goTypes,
		DependencyIndexes: file_proto_big_button_module_proto_depIdxs,
		MessageInfos:      file_proto_big_button_module_proto_msgTypes,
	}.Build()
	File_proto_big_button_module_proto = out.File
	file_proto_big_button_module_proto_goTypes = nil
	file_proto_big_button_module_proto_depIdxs = nil
}
