// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/bomb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bomb struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Modules       map[string]*Module     `protobuf:"bytes,2,rep,name=modules,proto3" json:"modules,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bomb) Reset() {
	*x = Bomb{}
	mi := &file_proto_bomb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bomb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bomb) ProtoMessage() {}

func (x *Bomb) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bomb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bomb.ProtoReflect.Descriptor instead.
func (*Bomb) Descriptor() ([]byte, []int) {
	return file_proto_bomb_proto_rawDescGZIP(), []int{0}
}

func (x *Bomb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bomb) GetModules() map[string]*Module {
	if x != nil {
		return x.Modules
	}
	return nil
}

var File_proto_bomb_proto protoreflect.FileDescriptor

const file_proto_bomb_proto_rawDesc = "" +
	"\n" +
	"\x10proto/bomb.proto\x12\x04bomb\x1a\x13proto/modules.proto\"\x96\x01\n" +
	"\x04Bomb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x121\n" +
	"\amodules\x18\x02 \x03(\v2\x17.bomb.Bomb.ModulesEntryR\amodules\x1aK\n" +
	"\fModulesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x05value\x18\x02 \x01(\v2\x0f.modules.ModuleR\x05value:\x028\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_bomb_proto_rawDescOnce sync.Once
	file_proto_bomb_proto_rawDescData []byte
)

func file_proto_bomb_proto_rawDescGZIP() []byte {
	file_proto_bomb_proto_rawDescOnce.Do(func() {
		file_proto_bomb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_bomb_proto_rawDesc), len(file_proto_bomb_proto_rawDesc)))
	})
	return file_proto_bomb_proto_rawDescData
}

var file_proto_bomb_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_bomb_proto_goTypes = []any{
	(*Bomb)(nil),   // 0: bomb.Bomb
	nil,            // 1: bomb.Bomb.ModulesEntry
	(*Module)(nil), // 2: modules.Module
}
var file_proto_bomb_proto_depIdxs = []int32{
	1, // 0: bomb.Bomb.modules:type_name -> bomb.Bomb.ModulesEntry
	2, // 1: bomb.Bomb.ModulesEntry.value:type_name -> modules.Module
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_bomb_proto_init() }
func file_proto_bomb_proto_init() {
	if File_proto_bomb_proto != nil {
		return
	}
	file_proto_modules_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_bomb_proto_rawDesc), len(file_proto_bomb_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_bomb_proto_goTypes,
		DependencyIndexes: file_proto_bomb_proto_depIdxs,
		MessageInfos:      file_proto_bomb_proto_msgTypes,
	}.Build()
	File_proto_bomb_proto = out.File
	file_proto_bomb_proto_goTypes = nil
	file_proto_bomb_proto_depIdxs = nil
}
