// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/game.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x04game\x1a\x12proto/player.proto2\x8f\x01\n" +
	"\vGameService\x12C\n" +
	"\n" +
	"CreateGame\x12\x19.player.CreateGameRequest\x1a\x1a.player.CreateGameResponse\x12;\n" +
	"\tSendInput\x12\x13.player.PlayerInput\x1a\x19.player.PlayerInputResultB\tZ\a./protob\x06proto3"

var file_proto_game_proto_goTypes = []any{
	(*CreateGameRequest)(nil),  // 0: player.CreateGameRequest
	(*PlayerInput)(nil),        // 1: player.PlayerInput
	(*CreateGameResponse)(nil), // 2: player.CreateGameResponse
	(*PlayerInputResult)(nil),  // 3: player.PlayerInputResult
}
var file_proto_game_proto_depIdxs = []int32{
	0, // 0: game.GameService.CreateGame:input_type -> player.CreateGameRequest
	1, // 1: game.GameService.SendInput:input_type -> player.PlayerInput
	2, // 2: game.GameService.CreateGame:output_type -> player.CreateGameResponse
	3, // 3: game.GameService.SendInput:output_type -> player.PlayerInputResult
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_player_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
