// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/maze_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MazeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     CardinalDirection      `protobuf:"varint,1,opt,name=direction,proto3,enum=common.CardinalDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MazeInput) Reset() {
	*x = MazeInput{}
	mi := &file_proto_maze_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MazeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeInput) ProtoMessage() {}

func (x *MazeInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maze_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeInput.ProtoReflect.Descriptor instead.
func (*MazeInput) Descriptor() ([]byte, []int) {
	return file_proto_maze_module_proto_rawDescGZIP(), []int{0}
}

func (x *MazeInput) GetDirection() CardinalDirection {
	if x != nil {
		return x.Direction
	}
	return CardinalDirection_UP
}

type MazeInputResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MazeState     *MazeState             `protobuf:"bytes,1,opt,name=maze_state,json=mazeState,proto3" json:"maze_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MazeInputResult) Reset() {
	*x = MazeInputResult{}
	mi := &file_proto_maze_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MazeInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeInputResult) ProtoMessage() {}

func (x *MazeInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maze_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeInputResult.ProtoReflect.Descriptor instead.
func (*MazeInputResult) Descriptor() ([]byte, []int) {
	return file_proto_maze_module_proto_rawDescGZIP(), []int{1}
}

func (x *MazeInputResult) GetMazeState() *MazeState {
	if x != nil {
		return x.MazeState
	}
	return nil
}

type MazeState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maze          *Maze                  `protobuf:"bytes,1,opt,name=maze,proto3" json:"maze,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MazeState) Reset() {
	*x = MazeState{}
	mi := &file_proto_maze_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MazeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeState) ProtoMessage() {}

func (x *MazeState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maze_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeState.ProtoReflect.Descriptor instead.
func (*MazeState) Descriptor() ([]byte, []int) {
	return file_proto_maze_module_proto_rawDescGZIP(), []int{2}
}

func (x *MazeState) GetMaze() *Maze {
	if x != nil {
		return x.Maze
	}
	return nil
}

// 6x6
type Maze struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Marker_1      *Point2D               `protobuf:"bytes,1,opt,name=marker_1,json=marker1,proto3" json:"marker_1,omitempty"`
	Marker_2      *Point2D               `protobuf:"bytes,2,opt,name=marker_2,json=marker2,proto3" json:"marker_2,omitempty"`
	Rows          []*MazeRow             `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Maze) Reset() {
	*x = Maze{}
	mi := &file_proto_maze_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Maze) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Maze) ProtoMessage() {}

func (x *Maze) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maze_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Maze.ProtoReflect.Descriptor instead.
func (*Maze) Descriptor() ([]byte, []int) {
	return file_proto_maze_module_proto_rawDescGZIP(), []int{3}
}

func (x *Maze) GetMarker_1() *Point2D {
	if x != nil {
		return x.Marker_1
	}
	return nil
}

func (x *Maze) GetMarker_2() *Point2D {
	if x != nil {
		return x.Marker_2
	}
	return nil
}

func (x *Maze) GetRows() []*MazeRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

type MazeRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*MazeCell            `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MazeRow) Reset() {
	*x = MazeRow{}
	mi := &file_proto_maze_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MazeRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeRow) ProtoMessage() {}

func (x *MazeRow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maze_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeRow.ProtoReflect.Descriptor instead.
func (*MazeRow) Descriptor() ([]byte, []int) {
	return file_proto_maze_module_proto_rawDescGZIP(), []int{4}
}

func (x *MazeRow) GetCells() []*MazeCell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type MazeCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Right         bool                   `protobuf:"varint,1,opt,name=right,proto3" json:"right,omitempty"`
	Botom         bool                   `protobuf:"varint,2,opt,name=botom,proto3" json:"botom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MazeCell) Reset() {
	*x = MazeCell{}
	mi := &file_proto_maze_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MazeCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeCell) ProtoMessage() {}

func (x *MazeCell) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maze_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeCell.ProtoReflect.Descriptor instead.
func (*MazeCell) Descriptor() ([]byte, []int) {
	return file_proto_maze_module_proto_rawDescGZIP(), []int{5}
}

func (x *MazeCell) GetRight() bool {
	if x != nil {
		return x.Right
	}
	return false
}

func (x *MazeCell) GetBotom() bool {
	if x != nil {
		return x.Botom
	}
	return false
}

var File_proto_maze_module_proto protoreflect.FileDescriptor

const file_proto_maze_module_proto_rawDesc = "" +
	"\n" +
	"\x17proto/maze_module.proto\x12\amodules\x1a\x12proto/common.proto\"D\n" +
	"\tMazeInput\x127\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x19.common.CardinalDirectionR\tdirection\"D\n" +
	"\x0fMazeInputResult\x121\n" +
	"\n" +
	"maze_state\x18\x01 \x01(\v2\x12.modules.MazeStateR\tmazeState\".\n" +
	"\tMazeState\x12!\n" +
	"\x04maze\x18\x01 \x01(\v2\r.modules.MazeR\x04maze\"\x84\x01\n" +
	"\x04Maze\x12*\n" +
	"\bmarker_1\x18\x01 \x01(\v2\x0f.common.Point2DR\amarker1\x12*\n" +
	"\bmarker_2\x18\x02 \x01(\v2\x0f.common.Point2DR\amarker2\x12$\n" +
	"\x04rows\x18\x03 \x03(\v2\x10.modules.MazeRowR\x04rows\"2\n" +
	"\aMazeRow\x12'\n" +
	"\x05cells\x18\x01 \x03(\v2\x11.modules.MazeCellR\x05cells\"6\n" +
	"\bMazeCell\x12\x14\n" +
	"\x05right\x18\x01 \x01(\bR\x05right\x12\x14\n" +
	"\x05botom\x18\x02 \x01(\bR\x05botomB\tZ\a./protob\x06proto3"

var (
	file_proto_maze_module_proto_rawDescOnce sync.Once
	file_proto_maze_module_proto_rawDescData []byte
)

func file_proto_maze_module_proto_rawDescGZIP() []byte {
	file_proto_maze_module_proto_rawDescOnce.Do(func() {
		file_proto_maze_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_maze_module_proto_rawDesc), len(file_proto_maze_module_proto_rawDesc)))
	})
	return file_proto_maze_module_proto_rawDescData
}

var file_proto_maze_module_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_maze_module_proto_goTypes = []any{
	(*MazeInput)(nil),       // 0: modules.MazeInput
	(*MazeInputResult)(nil), // 1: modules.MazeInputResult
	(*MazeState)(nil),       // 2: modules.MazeState
	(*Maze)(nil),            // 3: modules.Maze
	(*MazeRow)(nil),         // 4: modules.MazeRow
	(*MazeCell)(nil),        // 5: modules.MazeCell
	(CardinalDirection)(0),  // 6: common.CardinalDirection
	(*Point2D)(nil),         // 7: common.Point2D
}
var file_proto_maze_module_proto_depIdxs = []int32{
	6, // 0: modules.MazeInput.direction:type_name -> common.CardinalDirection
	2, // 1: modules.MazeInputResult.maze_state:type_name -> modules.MazeState
	3, // 2: modules.MazeState.maze:type_name -> modules.Maze
	7, // 3: modules.Maze.marker_1:type_name -> common.Point2D
	7, // 4: modules.Maze.marker_2:type_name -> common.Point2D
	4, // 5: modules.Maze.rows:type_name -> modules.MazeRow
	5, // 6: modules.MazeRow.cells:type_name -> modules.MazeCell
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_maze_module_proto_init() }
func file_proto_maze_module_proto_init() {
	if File_proto_maze_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_maze_module_proto_rawDesc), len(file_proto_maze_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_maze_module_proto_goTypes,
		DependencyIndexes: file_proto_maze_module_proto_depIdxs,
		MessageInfos:      file_proto_maze_module_proto_msgTypes,
	}.Build()
	File_proto_maze_module_proto = out.File
	file_proto_maze_module_proto_goTypes = nil
	file_proto_maze_module_proto_depIdxs = nil
}
