// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/maze_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MazeInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     CardinalDirection      `protobuf:"varint,1,opt,name=direction,proto3,enum=common.CardinalDirection" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MazeInput) Reset() {
	*x = MazeInput{}
	mi := &file_proto_maze_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MazeInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeInput) ProtoMessage() {}

func (x *MazeInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maze_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeInput.ProtoReflect.Descriptor instead.
func (*MazeInput) Descriptor() ([]byte, []int) {
	return file_proto_maze_module_proto_rawDescGZIP(), []int{0}
}

func (x *MazeInput) GetDirection() CardinalDirection {
	if x != nil {
		return x.Direction
	}
	return CardinalDirection_NORTH
}

type MazeInputResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MazeState     *MazeState             `protobuf:"bytes,1,opt,name=maze_state,json=mazeState,proto3" json:"maze_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MazeInputResult) Reset() {
	*x = MazeInputResult{}
	mi := &file_proto_maze_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MazeInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeInputResult) ProtoMessage() {}

func (x *MazeInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maze_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeInputResult.ProtoReflect.Descriptor instead.
func (*MazeInputResult) Descriptor() ([]byte, []int) {
	return file_proto_maze_module_proto_rawDescGZIP(), []int{1}
}

func (x *MazeInputResult) GetMazeState() *MazeState {
	if x != nil {
		return x.MazeState
	}
	return nil
}

type MazeState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Marker_1       *Point2D               `protobuf:"bytes,1,opt,name=marker_1,json=marker1,proto3" json:"marker_1,omitempty"`
	Marker_2       *Point2D               `protobuf:"bytes,2,opt,name=marker_2,json=marker2,proto3" json:"marker_2,omitempty"`
	PlayerPosition *Point2D               `protobuf:"bytes,3,opt,name=player_position,json=playerPosition,proto3" json:"player_position,omitempty"`
	GoalPosition   *Point2D               `protobuf:"bytes,4,opt,name=goal_position,json=goalPosition,proto3" json:"goal_position,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MazeState) Reset() {
	*x = MazeState{}
	mi := &file_proto_maze_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MazeState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeState) ProtoMessage() {}

func (x *MazeState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_maze_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeState.ProtoReflect.Descriptor instead.
func (*MazeState) Descriptor() ([]byte, []int) {
	return file_proto_maze_module_proto_rawDescGZIP(), []int{2}
}

func (x *MazeState) GetMarker_1() *Point2D {
	if x != nil {
		return x.Marker_1
	}
	return nil
}

func (x *MazeState) GetMarker_2() *Point2D {
	if x != nil {
		return x.Marker_2
	}
	return nil
}

func (x *MazeState) GetPlayerPosition() *Point2D {
	if x != nil {
		return x.PlayerPosition
	}
	return nil
}

func (x *MazeState) GetGoalPosition() *Point2D {
	if x != nil {
		return x.GoalPosition
	}
	return nil
}

var File_proto_maze_module_proto protoreflect.FileDescriptor

const file_proto_maze_module_proto_rawDesc = "" +
	"\n" +
	"\x17proto/maze_module.proto\x12\amodules\x1a\x12proto/common.proto\"D\n" +
	"\tMazeInput\x127\n" +
	"\tdirection\x18\x01 \x01(\x0e2\x19.common.CardinalDirectionR\tdirection\"D\n" +
	"\x0fMazeInputResult\x121\n" +
	"\n" +
	"maze_state\x18\x01 \x01(\v2\x12.modules.MazeStateR\tmazeState\"\xd3\x01\n" +
	"\tMazeState\x12*\n" +
	"\bmarker_1\x18\x01 \x01(\v2\x0f.common.Point2DR\amarker1\x12*\n" +
	"\bmarker_2\x18\x02 \x01(\v2\x0f.common.Point2DR\amarker2\x128\n" +
	"\x0fplayer_position\x18\x03 \x01(\v2\x0f.common.Point2DR\x0eplayerPosition\x124\n" +
	"\rgoal_position\x18\x04 \x01(\v2\x0f.common.Point2DR\fgoalPositionB\tZ\a./protob\x06proto3"

var (
	file_proto_maze_module_proto_rawDescOnce sync.Once
	file_proto_maze_module_proto_rawDescData []byte
)

func file_proto_maze_module_proto_rawDescGZIP() []byte {
	file_proto_maze_module_proto_rawDescOnce.Do(func() {
		file_proto_maze_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_maze_module_proto_rawDesc), len(file_proto_maze_module_proto_rawDesc)))
	})
	return file_proto_maze_module_proto_rawDescData
}

var file_proto_maze_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_maze_module_proto_goTypes = []any{
	(*MazeInput)(nil),       // 0: modules.MazeInput
	(*MazeInputResult)(nil), // 1: modules.MazeInputResult
	(*MazeState)(nil),       // 2: modules.MazeState
	(CardinalDirection)(0),  // 3: common.CardinalDirection
	(*Point2D)(nil),         // 4: common.Point2D
}
var file_proto_maze_module_proto_depIdxs = []int32{
	3, // 0: modules.MazeInput.direction:type_name -> common.CardinalDirection
	2, // 1: modules.MazeInputResult.maze_state:type_name -> modules.MazeState
	4, // 2: modules.MazeState.marker_1:type_name -> common.Point2D
	4, // 3: modules.MazeState.marker_2:type_name -> common.Point2D
	4, // 4: modules.MazeState.player_position:type_name -> common.Point2D
	4, // 5: modules.MazeState.goal_position:type_name -> common.Point2D
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_maze_module_proto_init() }
func file_proto_maze_module_proto_init() {
	if File_proto_maze_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_maze_module_proto_rawDesc), len(file_proto_maze_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_maze_module_proto_goTypes,
		DependencyIndexes: file_proto_maze_module_proto_depIdxs,
		MessageInfos:      file_proto_maze_module_proto_msgTypes,
	}.Build()
	File_proto_maze_module_proto = out.File
	file_proto_maze_module_proto_goTypes = nil
	file_proto_maze_module_proto_depIdxs = nil
}
