// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/modules.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BombFace int32

const (
	BombFace_FRONT BombFace = 0
	BombFace_BACK  BombFace = 1
)

// Enum value maps for BombFace.
var (
	BombFace_name = map[int32]string{
		0: "FRONT",
		1: "BACK",
	}
	BombFace_value = map[string]int32{
		"FRONT": 0,
		"BACK":  1,
	}
)

func (x BombFace) Enum() *BombFace {
	p := new(BombFace)
	*p = x
	return p
}

func (x BombFace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BombFace) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_modules_proto_enumTypes[0].Descriptor()
}

func (BombFace) Type() protoreflect.EnumType {
	return &file_proto_modules_proto_enumTypes[0]
}

func (x BombFace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BombFace.Descriptor instead.
func (BombFace) EnumDescriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{0}
}

type ModuleState_ModuleType int32

const (
	ModuleState_SIMPLE_WIRES ModuleState_ModuleType = 0
	ModuleState_PASSWORD     ModuleState_ModuleType = 1
)

// Enum value maps for ModuleState_ModuleType.
var (
	ModuleState_ModuleType_name = map[int32]string{
		0: "SIMPLE_WIRES",
		1: "PASSWORD",
	}
	ModuleState_ModuleType_value = map[string]int32{
		"SIMPLE_WIRES": 0,
		"PASSWORD":     1,
	}
)

func (x ModuleState_ModuleType) Enum() *ModuleState_ModuleType {
	p := new(ModuleState_ModuleType)
	*p = x
	return p
}

func (x ModuleState_ModuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleState_ModuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_modules_proto_enumTypes[1].Descriptor()
}

func (ModuleState_ModuleType) Type() protoreflect.EnumType {
	return &file_proto_modules_proto_enumTypes[1]
}

func (x ModuleState_ModuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleState_ModuleType.Descriptor instead.
func (ModuleState_ModuleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{1, 0}
}

type ModulePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Face          BombFace               `protobuf:"varint,1,opt,name=face,proto3,enum=modules.BombFace" json:"face,omitempty"`
	Row           int32                  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"` // 0-indexed
	Col           int32                  `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"` // 0-indexed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModulePosition) Reset() {
	*x = ModulePosition{}
	mi := &file_proto_modules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModulePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModulePosition) ProtoMessage() {}

func (x *ModulePosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModulePosition.ProtoReflect.Descriptor instead.
func (*ModulePosition) Descriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{0}
}

func (x *ModulePosition) GetFace() BombFace {
	if x != nil {
		return x.Face
	}
	return BombFace_FRONT
}

func (x *ModulePosition) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ModulePosition) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type ModuleState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Type          ModuleState_ModuleType `protobuf:"varint,2,opt,name=type,proto3,enum=modules.ModuleState_ModuleType" json:"type,omitempty"`
	Position      *ModulePosition        `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Solved        bool                   `protobuf:"varint,4,opt,name=solved,proto3" json:"solved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleState) Reset() {
	*x = ModuleState{}
	mi := &file_proto_modules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleState) ProtoMessage() {}

func (x *ModuleState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleState.ProtoReflect.Descriptor instead.
func (*ModuleState) Descriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{1}
}

func (x *ModuleState) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleState) GetType() ModuleState_ModuleType {
	if x != nil {
		return x.Type
	}
	return ModuleState_SIMPLE_WIRES
}

func (x *ModuleState) GetPosition() *ModulePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ModuleState) GetSolved() bool {
	if x != nil {
		return x.Solved
	}
	return false
}

var File_proto_modules_proto protoreflect.FileDescriptor

const file_proto_modules_proto_rawDesc = "" +
	"\n" +
	"\x13proto/modules.proto\x12\amodules\"[\n" +
	"\x0eModulePosition\x12%\n" +
	"\x04face\x18\x01 \x01(\x0e2\x11.modules.BombFaceR\x04face\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x03 \x01(\x05R\x03col\"\xda\x01\n" +
	"\vModuleState\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.modules.ModuleState.ModuleTypeR\x04type\x123\n" +
	"\bposition\x18\x03 \x01(\v2\x17.modules.ModulePositionR\bposition\x12\x16\n" +
	"\x06solved\x18\x04 \x01(\bR\x06solved\",\n" +
	"\n" +
	"ModuleType\x12\x10\n" +
	"\fSIMPLE_WIRES\x10\x00\x12\f\n" +
	"\bPASSWORD\x10\x01*\x1f\n" +
	"\bBombFace\x12\t\n" +
	"\x05FRONT\x10\x00\x12\b\n" +
	"\x04BACK\x10\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_modules_proto_rawDescOnce sync.Once
	file_proto_modules_proto_rawDescData []byte
)

func file_proto_modules_proto_rawDescGZIP() []byte {
	file_proto_modules_proto_rawDescOnce.Do(func() {
		file_proto_modules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_modules_proto_rawDesc), len(file_proto_modules_proto_rawDesc)))
	})
	return file_proto_modules_proto_rawDescData
}

var file_proto_modules_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_modules_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_modules_proto_goTypes = []any{
	(BombFace)(0),               // 0: modules.BombFace
	(ModuleState_ModuleType)(0), // 1: modules.ModuleState.ModuleType
	(*ModulePosition)(nil),      // 2: modules.ModulePosition
	(*ModuleState)(nil),         // 3: modules.ModuleState
}
var file_proto_modules_proto_depIdxs = []int32{
	0, // 0: modules.ModulePosition.face:type_name -> modules.BombFace
	1, // 1: modules.ModuleState.type:type_name -> modules.ModuleState.ModuleType
	2, // 2: modules.ModuleState.position:type_name -> modules.ModulePosition
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_modules_proto_init() }
func file_proto_modules_proto_init() {
	if File_proto_modules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_modules_proto_rawDesc), len(file_proto_modules_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_modules_proto_goTypes,
		DependencyIndexes: file_proto_modules_proto_depIdxs,
		EnumInfos:         file_proto_modules_proto_enumTypes,
		MessageInfos:      file_proto_modules_proto_msgTypes,
	}.Build()
	File_proto_modules_proto = out.File
	file_proto_modules_proto_goTypes = nil
	file_proto_modules_proto_depIdxs = nil
}
