// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/modules.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleType int32

const (
	ModuleType_SIMPLE_WIRES ModuleType = 0
	ModuleType_PASSWORD     ModuleType = 1
)

// Enum value maps for ModuleType.
var (
	ModuleType_name = map[int32]string{
		0: "SIMPLE_WIRES",
		1: "PASSWORD",
	}
	ModuleType_value = map[string]int32{
		"SIMPLE_WIRES": 0,
		"PASSWORD":     1,
	}
)

func (x ModuleType) Enum() *ModuleType {
	p := new(ModuleType)
	*p = x
	return p
}

func (x ModuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_modules_proto_enumTypes[0].Descriptor()
}

func (ModuleType) Type() protoreflect.EnumType {
	return &file_proto_modules_proto_enumTypes[0]
}

func (x ModuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleType.Descriptor instead.
func (ModuleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{0}
}

type BombFace int32

const (
	BombFace_FRONT BombFace = 0
	BombFace_BACK  BombFace = 1
)

// Enum value maps for BombFace.
var (
	BombFace_name = map[int32]string{
		0: "FRONT",
		1: "BACK",
	}
	BombFace_value = map[string]int32{
		"FRONT": 0,
		"BACK":  1,
	}
)

func (x BombFace) Enum() *BombFace {
	p := new(BombFace)
	*p = x
	return p
}

func (x BombFace) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BombFace) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_modules_proto_enumTypes[1].Descriptor()
}

func (BombFace) Type() protoreflect.EnumType {
	return &file_proto_modules_proto_enumTypes[1]
}

func (x BombFace) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BombFace.Descriptor instead.
func (BombFace) EnumDescriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{1}
}

type ModuleState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Type          ModuleType             `protobuf:"varint,2,opt,name=type,proto3,enum=modules.ModuleType" json:"type,omitempty"`
	Face          BombFace               `protobuf:"varint,3,opt,name=face,proto3,enum=modules.BombFace" json:"face,omitempty"`
	Solved        bool                   `protobuf:"varint,4,opt,name=solved,proto3" json:"solved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleState) Reset() {
	*x = ModuleState{}
	mi := &file_proto_modules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleState) ProtoMessage() {}

func (x *ModuleState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleState.ProtoReflect.Descriptor instead.
func (*ModuleState) Descriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleState) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *ModuleState) GetType() ModuleType {
	if x != nil {
		return x.Type
	}
	return ModuleType_SIMPLE_WIRES
}

func (x *ModuleState) GetFace() BombFace {
	if x != nil {
		return x.Face
	}
	return BombFace_FRONT
}

func (x *ModuleState) GetSolved() bool {
	if x != nil {
		return x.Solved
	}
	return false
}

type InputResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputResult) Reset() {
	*x = InputResult{}
	mi := &file_proto_modules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputResult) ProtoMessage() {}

func (x *InputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputResult.ProtoReflect.Descriptor instead.
func (*InputResult) Descriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{1}
}

func (x *InputResult) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *InputResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CutWireInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	WireIndex     int32                  `protobuf:"varint,2,opt,name=wire_index,json=wireIndex,proto3" json:"wire_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CutWireInput) Reset() {
	*x = CutWireInput{}
	mi := &file_proto_modules_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CutWireInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CutWireInput) ProtoMessage() {}

func (x *CutWireInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CutWireInput.ProtoReflect.Descriptor instead.
func (*CutWireInput) Descriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{2}
}

func (x *CutWireInput) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *CutWireInput) GetWireIndex() int32 {
	if x != nil {
		return x.WireIndex
	}
	return 0
}

type SubmitPasswordInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModuleId      string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPasswordInput) Reset() {
	*x = SubmitPasswordInput{}
	mi := &file_proto_modules_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPasswordInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPasswordInput) ProtoMessage() {}

func (x *SubmitPasswordInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPasswordInput.ProtoReflect.Descriptor instead.
func (*SubmitPasswordInput) Descriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitPasswordInput) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *SubmitPasswordInput) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_proto_modules_proto protoreflect.FileDescriptor

const file_proto_modules_proto_rawDesc = "" +
	"\n" +
	"\x13proto/modules.proto\x12\amodules\"\x92\x01\n" +
	"\vModuleState\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12'\n" +
	"\x04type\x18\x02 \x01(\x0e2\x13.modules.ModuleTypeR\x04type\x12%\n" +
	"\x04face\x18\x03 \x01(\x0e2\x11.modules.BombFaceR\x04face\x12\x16\n" +
	"\x06solved\x18\x04 \x01(\bR\x06solved\"D\n" +
	"\vInputResult\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"J\n" +
	"\fCutWireInput\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x1d\n" +
	"\n" +
	"wire_index\x18\x02 \x01(\x05R\twireIndex\"N\n" +
	"\x13SubmitPasswordInput\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword*,\n" +
	"\n" +
	"ModuleType\x12\x10\n" +
	"\fSIMPLE_WIRES\x10\x00\x12\f\n" +
	"\bPASSWORD\x10\x01*\x1f\n" +
	"\bBombFace\x12\t\n" +
	"\x05FRONT\x10\x00\x12\b\n" +
	"\x04BACK\x10\x01B\tZ\a./protob\x06proto3"

var (
	file_proto_modules_proto_rawDescOnce sync.Once
	file_proto_modules_proto_rawDescData []byte
)

func file_proto_modules_proto_rawDescGZIP() []byte {
	file_proto_modules_proto_rawDescOnce.Do(func() {
		file_proto_modules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_modules_proto_rawDesc), len(file_proto_modules_proto_rawDesc)))
	})
	return file_proto_modules_proto_rawDescData
}

var file_proto_modules_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_modules_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_modules_proto_goTypes = []any{
	(ModuleType)(0),             // 0: modules.ModuleType
	(BombFace)(0),               // 1: modules.BombFace
	(*ModuleState)(nil),         // 2: modules.ModuleState
	(*InputResult)(nil),         // 3: modules.InputResult
	(*CutWireInput)(nil),        // 4: modules.CutWireInput
	(*SubmitPasswordInput)(nil), // 5: modules.SubmitPasswordInput
}
var file_proto_modules_proto_depIdxs = []int32{
	0, // 0: modules.ModuleState.type:type_name -> modules.ModuleType
	1, // 1: modules.ModuleState.face:type_name -> modules.BombFace
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_modules_proto_init() }
func file_proto_modules_proto_init() {
	if File_proto_modules_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_modules_proto_rawDesc), len(file_proto_modules_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_modules_proto_goTypes,
		DependencyIndexes: file_proto_modules_proto_depIdxs,
		EnumInfos:         file_proto_modules_proto_enumTypes,
		MessageInfos:      file_proto_modules_proto_msgTypes,
	}.Build()
	File_proto_modules_proto = out.File
	file_proto_modules_proto_goTypes = nil
	file_proto_modules_proto_depIdxs = nil
}
