// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/needy_knob_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Doesn't need any fields. If input is received, rotate clockwise.
type NeedyKnobInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedyKnobInput) Reset() {
	*x = NeedyKnobInput{}
	mi := &file_proto_needy_knob_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedyKnobInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedyKnobInput) ProtoMessage() {}

func (x *NeedyKnobInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needy_knob_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedyKnobInput.ProtoReflect.Descriptor instead.
func (*NeedyKnobInput) Descriptor() ([]byte, []int) {
	return file_proto_needy_knob_module_proto_rawDescGZIP(), []int{0}
}

type NeedyKnobInputResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NeedyKnobState *NeedyKnobState        `protobuf:"bytes,1,opt,name=needy_knob_state,json=needyKnobState,proto3" json:"needy_knob_state,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NeedyKnobInputResult) Reset() {
	*x = NeedyKnobInputResult{}
	mi := &file_proto_needy_knob_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedyKnobInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedyKnobInputResult) ProtoMessage() {}

func (x *NeedyKnobInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needy_knob_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedyKnobInputResult.ProtoReflect.Descriptor instead.
func (*NeedyKnobInputResult) Descriptor() ([]byte, []int) {
	return file_proto_needy_knob_module_proto_rawDescGZIP(), []int{1}
}

func (x *NeedyKnobInputResult) GetNeedyKnobState() *NeedyKnobState {
	if x != nil {
		return x.NeedyKnobState
	}
	return nil
}

type NeedyKnobState struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	DisplayedPatternFirstRow  []bool                 `protobuf:"varint,1,rep,packed,name=displayed_pattern_first_row,json=displayedPatternFirstRow,proto3" json:"displayed_pattern_first_row,omitempty"`
	DisplayedPatternSecondRow []bool                 `protobuf:"varint,2,rep,packed,name=displayed_pattern_second_row,json=displayedPatternSecondRow,proto3" json:"displayed_pattern_second_row,omitempty"`
	DialDirection             CardinalDirection      `protobuf:"varint,3,opt,name=dial_direction,json=dialDirection,proto3,enum=common.CardinalDirection" json:"dial_direction,omitempty"`
	CountdownStartedAt        int64                  `protobuf:"varint,4,opt,name=countdown_started_at,json=countdownStartedAt,proto3" json:"countdown_started_at,omitempty"`
	CountdownDuration         int32                  `protobuf:"varint,5,opt,name=countdown_duration,json=countdownDuration,proto3" json:"countdown_duration,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *NeedyKnobState) Reset() {
	*x = NeedyKnobState{}
	mi := &file_proto_needy_knob_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedyKnobState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedyKnobState) ProtoMessage() {}

func (x *NeedyKnobState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needy_knob_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedyKnobState.ProtoReflect.Descriptor instead.
func (*NeedyKnobState) Descriptor() ([]byte, []int) {
	return file_proto_needy_knob_module_proto_rawDescGZIP(), []int{2}
}

func (x *NeedyKnobState) GetDisplayedPatternFirstRow() []bool {
	if x != nil {
		return x.DisplayedPatternFirstRow
	}
	return nil
}

func (x *NeedyKnobState) GetDisplayedPatternSecondRow() []bool {
	if x != nil {
		return x.DisplayedPatternSecondRow
	}
	return nil
}

func (x *NeedyKnobState) GetDialDirection() CardinalDirection {
	if x != nil {
		return x.DialDirection
	}
	return CardinalDirection_NORTH
}

func (x *NeedyKnobState) GetCountdownStartedAt() int64 {
	if x != nil {
		return x.CountdownStartedAt
	}
	return 0
}

func (x *NeedyKnobState) GetCountdownDuration() int32 {
	if x != nil {
		return x.CountdownDuration
	}
	return 0
}

var File_proto_needy_knob_module_proto protoreflect.FileDescriptor

const file_proto_needy_knob_module_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/needy_knob_module.proto\x12\amodules\x1a\x12proto/common.proto\"\x10\n" +
	"\x0eNeedyKnobInput\"Y\n" +
	"\x14NeedyKnobInputResult\x12A\n" +
	"\x10needy_knob_state\x18\x01 \x01(\v2\x17.modules.NeedyKnobStateR\x0eneedyKnobState\"\xb3\x02\n" +
	"\x0eNeedyKnobState\x12=\n" +
	"\x1bdisplayed_pattern_first_row\x18\x01 \x03(\bR\x18displayedPatternFirstRow\x12?\n" +
	"\x1cdisplayed_pattern_second_row\x18\x02 \x03(\bR\x19displayedPatternSecondRow\x12@\n" +
	"\x0edial_direction\x18\x03 \x01(\x0e2\x19.common.CardinalDirectionR\rdialDirection\x120\n" +
	"\x14countdown_started_at\x18\x04 \x01(\x03R\x12countdownStartedAt\x12-\n" +
	"\x12countdown_duration\x18\x05 \x01(\x05R\x11countdownDurationB\tZ\a./protob\x06proto3"

var (
	file_proto_needy_knob_module_proto_rawDescOnce sync.Once
	file_proto_needy_knob_module_proto_rawDescData []byte
)

func file_proto_needy_knob_module_proto_rawDescGZIP() []byte {
	file_proto_needy_knob_module_proto_rawDescOnce.Do(func() {
		file_proto_needy_knob_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_needy_knob_module_proto_rawDesc), len(file_proto_needy_knob_module_proto_rawDesc)))
	})
	return file_proto_needy_knob_module_proto_rawDescData
}

var file_proto_needy_knob_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_needy_knob_module_proto_goTypes = []any{
	(*NeedyKnobInput)(nil),       // 0: modules.NeedyKnobInput
	(*NeedyKnobInputResult)(nil), // 1: modules.NeedyKnobInputResult
	(*NeedyKnobState)(nil),       // 2: modules.NeedyKnobState
	(CardinalDirection)(0),       // 3: common.CardinalDirection
}
var file_proto_needy_knob_module_proto_depIdxs = []int32{
	2, // 0: modules.NeedyKnobInputResult.needy_knob_state:type_name -> modules.NeedyKnobState
	3, // 1: modules.NeedyKnobState.dial_direction:type_name -> common.CardinalDirection
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_needy_knob_module_proto_init() }
func file_proto_needy_knob_module_proto_init() {
	if File_proto_needy_knob_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_needy_knob_module_proto_rawDesc), len(file_proto_needy_knob_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_needy_knob_module_proto_goTypes,
		DependencyIndexes: file_proto_needy_knob_module_proto_depIdxs,
		MessageInfos:      file_proto_needy_knob_module_proto_msgTypes,
	}.Build()
	File_proto_needy_knob_module_proto = out.File
	file_proto_needy_knob_module_proto_goTypes = nil
	file_proto_needy_knob_module_proto_depIdxs = nil
}
