// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/needy_vent_gas_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NeedyVentGasInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         bool                   `protobuf:"varint,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedyVentGasInput) Reset() {
	*x = NeedyVentGasInput{}
	mi := &file_proto_needy_vent_gas_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedyVentGasInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedyVentGasInput) ProtoMessage() {}

func (x *NeedyVentGasInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needy_vent_gas_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedyVentGasInput.ProtoReflect.Descriptor instead.
func (*NeedyVentGasInput) Descriptor() ([]byte, []int) {
	return file_proto_needy_vent_gas_module_proto_rawDescGZIP(), []int{0}
}

func (x *NeedyVentGasInput) GetInput() bool {
	if x != nil {
		return x.Input
	}
	return false
}

type NeedyVentGasInputResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NeedyVentGasState *NeedyVentGasState     `protobuf:"bytes,1,opt,name=needy_vent_gas_state,json=needyVentGasState,proto3" json:"needy_vent_gas_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NeedyVentGasInputResult) Reset() {
	*x = NeedyVentGasInputResult{}
	mi := &file_proto_needy_vent_gas_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedyVentGasInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedyVentGasInputResult) ProtoMessage() {}

func (x *NeedyVentGasInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needy_vent_gas_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedyVentGasInputResult.ProtoReflect.Descriptor instead.
func (*NeedyVentGasInputResult) Descriptor() ([]byte, []int) {
	return file_proto_needy_vent_gas_module_proto_rawDescGZIP(), []int{1}
}

func (x *NeedyVentGasInputResult) GetNeedyVentGasState() *NeedyVentGasState {
	if x != nil {
		return x.NeedyVentGasState
	}
	return nil
}

type NeedyVentGasState struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DisplayedQuestion  string                 `protobuf:"bytes,1,opt,name=displayed_question,json=displayedQuestion,proto3" json:"displayed_question,omitempty"`
	CountdownStartedAt int64                  `protobuf:"varint,2,opt,name=countdown_started_at,json=countdownStartedAt,proto3" json:"countdown_started_at,omitempty"`
	CountdownDuration  int32                  `protobuf:"varint,3,opt,name=countdown_duration,json=countdownDuration,proto3" json:"countdown_duration,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NeedyVentGasState) Reset() {
	*x = NeedyVentGasState{}
	mi := &file_proto_needy_vent_gas_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedyVentGasState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedyVentGasState) ProtoMessage() {}

func (x *NeedyVentGasState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_needy_vent_gas_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedyVentGasState.ProtoReflect.Descriptor instead.
func (*NeedyVentGasState) Descriptor() ([]byte, []int) {
	return file_proto_needy_vent_gas_module_proto_rawDescGZIP(), []int{2}
}

func (x *NeedyVentGasState) GetDisplayedQuestion() string {
	if x != nil {
		return x.DisplayedQuestion
	}
	return ""
}

func (x *NeedyVentGasState) GetCountdownStartedAt() int64 {
	if x != nil {
		return x.CountdownStartedAt
	}
	return 0
}

func (x *NeedyVentGasState) GetCountdownDuration() int32 {
	if x != nil {
		return x.CountdownDuration
	}
	return 0
}

var File_proto_needy_vent_gas_module_proto protoreflect.FileDescriptor

const file_proto_needy_vent_gas_module_proto_rawDesc = "" +
	"\n" +
	"!proto/needy_vent_gas_module.proto\x12\amodules\x1a\x12proto/common.proto\")\n" +
	"\x11NeedyVentGasInput\x12\x14\n" +
	"\x05input\x18\x01 \x01(\bR\x05input\"f\n" +
	"\x17NeedyVentGasInputResult\x12K\n" +
	"\x14needy_vent_gas_state\x18\x01 \x01(\v2\x1a.modules.NeedyVentGasStateR\x11needyVentGasState\"\xa3\x01\n" +
	"\x11NeedyVentGasState\x12-\n" +
	"\x12displayed_question\x18\x01 \x01(\tR\x11displayedQuestion\x120\n" +
	"\x14countdown_started_at\x18\x02 \x01(\x03R\x12countdownStartedAt\x12-\n" +
	"\x12countdown_duration\x18\x03 \x01(\x05R\x11countdownDurationB\tZ\a./protob\x06proto3"

var (
	file_proto_needy_vent_gas_module_proto_rawDescOnce sync.Once
	file_proto_needy_vent_gas_module_proto_rawDescData []byte
)

func file_proto_needy_vent_gas_module_proto_rawDescGZIP() []byte {
	file_proto_needy_vent_gas_module_proto_rawDescOnce.Do(func() {
		file_proto_needy_vent_gas_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_needy_vent_gas_module_proto_rawDesc), len(file_proto_needy_vent_gas_module_proto_rawDesc)))
	})
	return file_proto_needy_vent_gas_module_proto_rawDescData
}

var file_proto_needy_vent_gas_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_needy_vent_gas_module_proto_goTypes = []any{
	(*NeedyVentGasInput)(nil),       // 0: modules.NeedyVentGasInput
	(*NeedyVentGasInputResult)(nil), // 1: modules.NeedyVentGasInputResult
	(*NeedyVentGasState)(nil),       // 2: modules.NeedyVentGasState
}
var file_proto_needy_vent_gas_module_proto_depIdxs = []int32{
	2, // 0: modules.NeedyVentGasInputResult.needy_vent_gas_state:type_name -> modules.NeedyVentGasState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_needy_vent_gas_module_proto_init() }
func file_proto_needy_vent_gas_module_proto_init() {
	if File_proto_needy_vent_gas_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_needy_vent_gas_module_proto_rawDesc), len(file_proto_needy_vent_gas_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_needy_vent_gas_module_proto_goTypes,
		DependencyIndexes: file_proto_needy_vent_gas_module_proto_depIdxs,
		MessageInfos:      file_proto_needy_vent_gas_module_proto_msgTypes,
	}.Build()
	File_proto_needy_vent_gas_module_proto = out.File
	file_proto_needy_vent_gas_module_proto_goTypes = nil
	file_proto_needy_vent_gas_module_proto_depIdxs = nil
}
