// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/password_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LetterChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LetterIndex   int32                  `protobuf:"varint,1,opt,name=letter_index,json=letterIndex,proto3" json:"letter_index,omitempty"`
	Direction     IncrementDecrement     `protobuf:"varint,2,opt,name=direction,proto3,enum=common.IncrementDecrement" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LetterChange) Reset() {
	*x = LetterChange{}
	mi := &file_proto_password_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LetterChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LetterChange) ProtoMessage() {}

func (x *LetterChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_password_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LetterChange.ProtoReflect.Descriptor instead.
func (*LetterChange) Descriptor() ([]byte, []int) {
	return file_proto_password_module_proto_rawDescGZIP(), []int{0}
}

func (x *LetterChange) GetLetterIndex() int32 {
	if x != nil {
		return x.LetterIndex
	}
	return 0
}

func (x *LetterChange) GetDirection() IncrementDecrement {
	if x != nil {
		return x.Direction
	}
	return IncrementDecrement_INCREMENT
}

type PasswordSubmit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordSubmit) Reset() {
	*x = PasswordSubmit{}
	mi := &file_proto_password_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordSubmit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordSubmit) ProtoMessage() {}

func (x *PasswordSubmit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_password_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordSubmit.ProtoReflect.Descriptor instead.
func (*PasswordSubmit) Descriptor() ([]byte, []int) {
	return file_proto_password_module_proto_rawDescGZIP(), []int{1}
}

type PasswordInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*PasswordInput_LetterChange
	//	*PasswordInput_Submit
	Input         isPasswordInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordInput) Reset() {
	*x = PasswordInput{}
	mi := &file_proto_password_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordInput) ProtoMessage() {}

func (x *PasswordInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_password_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordInput.ProtoReflect.Descriptor instead.
func (*PasswordInput) Descriptor() ([]byte, []int) {
	return file_proto_password_module_proto_rawDescGZIP(), []int{2}
}

func (x *PasswordInput) GetInput() isPasswordInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *PasswordInput) GetLetterChange() *LetterChange {
	if x != nil {
		if x, ok := x.Input.(*PasswordInput_LetterChange); ok {
			return x.LetterChange
		}
	}
	return nil
}

func (x *PasswordInput) GetSubmit() *PasswordSubmit {
	if x != nil {
		if x, ok := x.Input.(*PasswordInput_Submit); ok {
			return x.Submit
		}
	}
	return nil
}

type isPasswordInput_Input interface {
	isPasswordInput_Input()
}

type PasswordInput_LetterChange struct {
	LetterChange *LetterChange `protobuf:"bytes,1,opt,name=letter_change,json=letterChange,proto3,oneof"`
}

type PasswordInput_Submit struct {
	Submit *PasswordSubmit `protobuf:"bytes,2,opt,name=submit,proto3,oneof"`
}

func (*PasswordInput_LetterChange) isPasswordInput_Input() {}

func (*PasswordInput_Submit) isPasswordInput_Input() {}

type PasswordInputResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PasswordState *PasswordState         `protobuf:"bytes,1,opt,name=password_state,json=passwordState,proto3" json:"password_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordInputResult) Reset() {
	*x = PasswordInputResult{}
	mi := &file_proto_password_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordInputResult) ProtoMessage() {}

func (x *PasswordInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_password_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordInputResult.ProtoReflect.Descriptor instead.
func (*PasswordInputResult) Descriptor() ([]byte, []int) {
	return file_proto_password_module_proto_rawDescGZIP(), []int{3}
}

func (x *PasswordInputResult) GetPasswordState() *PasswordState {
	if x != nil {
		return x.PasswordState
	}
	return nil
}

type PasswordState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains the current letters in order
	Letters       string `protobuf:"bytes,1,opt,name=letters,proto3" json:"letters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordState) Reset() {
	*x = PasswordState{}
	mi := &file_proto_password_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordState) ProtoMessage() {}

func (x *PasswordState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_password_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordState.ProtoReflect.Descriptor instead.
func (*PasswordState) Descriptor() ([]byte, []int) {
	return file_proto_password_module_proto_rawDescGZIP(), []int{4}
}

func (x *PasswordState) GetLetters() string {
	if x != nil {
		return x.Letters
	}
	return ""
}

var File_proto_password_module_proto protoreflect.FileDescriptor

const file_proto_password_module_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/password_module.proto\x12\amodules\x1a\x12proto/common.proto\"k\n" +
	"\fLetterChange\x12!\n" +
	"\fletter_index\x18\x01 \x01(\x05R\vletterIndex\x128\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1a.common.IncrementDecrementR\tdirection\"\x10\n" +
	"\x0ePasswordSubmit\"\x89\x01\n" +
	"\rPasswordInput\x12<\n" +
	"\rletter_change\x18\x01 \x01(\v2\x15.modules.LetterChangeH\x00R\fletterChange\x121\n" +
	"\x06submit\x18\x02 \x01(\v2\x17.modules.PasswordSubmitH\x00R\x06submitB\a\n" +
	"\x05input\"T\n" +
	"\x13PasswordInputResult\x12=\n" +
	"\x0epassword_state\x18\x01 \x01(\v2\x16.modules.PasswordStateR\rpasswordState\")\n" +
	"\rPasswordState\x12\x18\n" +
	"\aletters\x18\x01 \x01(\tR\alettersB\tZ\a./protob\x06proto3"

var (
	file_proto_password_module_proto_rawDescOnce sync.Once
	file_proto_password_module_proto_rawDescData []byte
)

func file_proto_password_module_proto_rawDescGZIP() []byte {
	file_proto_password_module_proto_rawDescOnce.Do(func() {
		file_proto_password_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_password_module_proto_rawDesc), len(file_proto_password_module_proto_rawDesc)))
	})
	return file_proto_password_module_proto_rawDescData
}

var file_proto_password_module_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_password_module_proto_goTypes = []any{
	(*LetterChange)(nil),        // 0: modules.LetterChange
	(*PasswordSubmit)(nil),      // 1: modules.PasswordSubmit
	(*PasswordInput)(nil),       // 2: modules.PasswordInput
	(*PasswordInputResult)(nil), // 3: modules.PasswordInputResult
	(*PasswordState)(nil),       // 4: modules.PasswordState
	(IncrementDecrement)(0),     // 5: common.IncrementDecrement
}
var file_proto_password_module_proto_depIdxs = []int32{
	5, // 0: modules.LetterChange.direction:type_name -> common.IncrementDecrement
	0, // 1: modules.PasswordInput.letter_change:type_name -> modules.LetterChange
	1, // 2: modules.PasswordInput.submit:type_name -> modules.PasswordSubmit
	4, // 3: modules.PasswordInputResult.password_state:type_name -> modules.PasswordState
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_password_module_proto_init() }
func file_proto_password_module_proto_init() {
	if File_proto_password_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_password_module_proto_msgTypes[2].OneofWrappers = []any{
		(*PasswordInput_LetterChange)(nil),
		(*PasswordInput_Submit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_password_module_proto_rawDesc), len(file_proto_password_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_password_module_proto_goTypes,
		DependencyIndexes: file_proto_password_module_proto_depIdxs,
		MessageInfos:      file_proto_password_module_proto_msgTypes,
	}.Build()
	File_proto_password_module_proto = out.File
	file_proto_password_module_proto_goTypes = nil
	file_proto_password_module_proto_depIdxs = nil
}
