// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/password_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LetterChange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LetterIndex   int32                  `protobuf:"varint,1,opt,name=letter_index,json=letterIndex,proto3" json:"letter_index,omitempty"`
	Direction     IncrementDecrement     `protobuf:"varint,2,opt,name=direction,proto3,enum=common.IncrementDecrement" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LetterChange) Reset() {
	*x = LetterChange{}
	mi := &file_proto_password_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LetterChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LetterChange) ProtoMessage() {}

func (x *LetterChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_password_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LetterChange.ProtoReflect.Descriptor instead.
func (*LetterChange) Descriptor() ([]byte, []int) {
	return file_proto_password_module_proto_rawDescGZIP(), []int{0}
}

func (x *LetterChange) GetLetterIndex() int32 {
	if x != nil {
		return x.LetterIndex
	}
	return 0
}

func (x *LetterChange) GetDirection() IncrementDecrement {
	if x != nil {
		return x.Direction
	}
	return IncrementDecrement_INCREMENT
}

type PasswordInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*PasswordInput_LetterChange
	//	*PasswordInput_Submit
	Input         isPasswordInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordInput) Reset() {
	*x = PasswordInput{}
	mi := &file_proto_password_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordInput) ProtoMessage() {}

func (x *PasswordInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_password_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordInput.ProtoReflect.Descriptor instead.
func (*PasswordInput) Descriptor() ([]byte, []int) {
	return file_proto_password_module_proto_rawDescGZIP(), []int{1}
}

func (x *PasswordInput) GetInput() isPasswordInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *PasswordInput) GetLetterChange() *LetterChange {
	if x != nil {
		if x, ok := x.Input.(*PasswordInput_LetterChange); ok {
			return x.LetterChange
		}
	}
	return nil
}

func (x *PasswordInput) GetSubmit() bool {
	if x != nil {
		if x, ok := x.Input.(*PasswordInput_Submit); ok {
			return x.Submit
		}
	}
	return false
}

type isPasswordInput_Input interface {
	isPasswordInput_Input()
}

type PasswordInput_LetterChange struct {
	LetterChange *LetterChange `protobuf:"bytes,1,opt,name=letter_change,json=letterChange,proto3,oneof"`
}

type PasswordInput_Submit struct {
	Submit bool `protobuf:"varint,2,opt,name=submit,proto3,oneof"`
}

func (*PasswordInput_LetterChange) isPasswordInput_Input() {}

func (*PasswordInput_Submit) isPasswordInput_Input() {}

var File_proto_password_module_proto protoreflect.FileDescriptor

const file_proto_password_module_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/password_module.proto\x12\amodules\x1a\x12proto/common.proto\"k\n" +
	"\fLetterChange\x12!\n" +
	"\fletter_index\x18\x01 \x01(\x05R\vletterIndex\x128\n" +
	"\tdirection\x18\x02 \x01(\x0e2\x1a.common.IncrementDecrementR\tdirection\"p\n" +
	"\rPasswordInput\x12<\n" +
	"\rletter_change\x18\x01 \x01(\v2\x15.modules.LetterChangeH\x00R\fletterChange\x12\x18\n" +
	"\x06submit\x18\x02 \x01(\bH\x00R\x06submitB\a\n" +
	"\x05inputB\tZ\a./protob\x06proto3"

var (
	file_proto_password_module_proto_rawDescOnce sync.Once
	file_proto_password_module_proto_rawDescData []byte
)

func file_proto_password_module_proto_rawDescGZIP() []byte {
	file_proto_password_module_proto_rawDescOnce.Do(func() {
		file_proto_password_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_password_module_proto_rawDesc), len(file_proto_password_module_proto_rawDesc)))
	})
	return file_proto_password_module_proto_rawDescData
}

var file_proto_password_module_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_password_module_proto_goTypes = []any{
	(*LetterChange)(nil),    // 0: modules.LetterChange
	(*PasswordInput)(nil),   // 1: modules.PasswordInput
	(IncrementDecrement)(0), // 2: common.IncrementDecrement
}
var file_proto_password_module_proto_depIdxs = []int32{
	2, // 0: modules.LetterChange.direction:type_name -> common.IncrementDecrement
	0, // 1: modules.PasswordInput.letter_change:type_name -> modules.LetterChange
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_password_module_proto_init() }
func file_proto_password_module_proto_init() {
	if File_proto_password_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	file_proto_password_module_proto_msgTypes[1].OneofWrappers = []any{
		(*PasswordInput_LetterChange)(nil),
		(*PasswordInput_Submit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_password_module_proto_rawDesc), len(file_proto_password_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_password_module_proto_goTypes,
		DependencyIndexes: file_proto_password_module_proto_depIdxs,
		MessageInfos:      file_proto_password_module_proto_msgTypes,
	}.Build()
	File_proto_password_module_proto = out.File
	file_proto_password_module_proto_goTypes = nil
	file_proto_password_module_proto_depIdxs = nil
}
