// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/player.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateGameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameRequest) Reset() {
	*x = CreateGameRequest{}
	mi := &file_proto_player_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameRequest) ProtoMessage() {}

func (x *CreateGameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameRequest.ProtoReflect.Descriptor instead.
func (*CreateGameRequest) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{0}
}

type CreateGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameResponse) Reset() {
	*x = CreateGameResponse{}
	mi := &file_proto_player_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameResponse) ProtoMessage() {}

func (x *CreateGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameResponse.ProtoReflect.Descriptor instead.
func (*CreateGameResponse) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGameResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type PlayerInput struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	BombId    string                 `protobuf:"bytes,2,opt,name=bomb_id,json=bombId,proto3" json:"bomb_id,omitempty"`
	ModuleId  string                 `protobuf:"bytes,3,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	// Types that are valid to be assigned to Input:
	//
	//	*PlayerInput_SimpleWiresInput
	//	*PlayerInput_PasswordInput
	//	*PlayerInput_BigButtonInput
	//	*PlayerInput_SimonSaysInput
	Input         isPlayerInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInput) Reset() {
	*x = PlayerInput{}
	mi := &file_proto_player_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInput) ProtoMessage() {}

func (x *PlayerInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInput.ProtoReflect.Descriptor instead.
func (*PlayerInput) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerInput) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PlayerInput) GetBombId() string {
	if x != nil {
		return x.BombId
	}
	return ""
}

func (x *PlayerInput) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *PlayerInput) GetInput() isPlayerInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *PlayerInput) GetSimpleWiresInput() *SimpleWiresInput {
	if x != nil {
		if x, ok := x.Input.(*PlayerInput_SimpleWiresInput); ok {
			return x.SimpleWiresInput
		}
	}
	return nil
}

func (x *PlayerInput) GetPasswordInput() *PasswordInput {
	if x != nil {
		if x, ok := x.Input.(*PlayerInput_PasswordInput); ok {
			return x.PasswordInput
		}
	}
	return nil
}

func (x *PlayerInput) GetBigButtonInput() *BigButtonInput {
	if x != nil {
		if x, ok := x.Input.(*PlayerInput_BigButtonInput); ok {
			return x.BigButtonInput
		}
	}
	return nil
}

func (x *PlayerInput) GetSimonSaysInput() *SimonSaysInput {
	if x != nil {
		if x, ok := x.Input.(*PlayerInput_SimonSaysInput); ok {
			return x.SimonSaysInput
		}
	}
	return nil
}

type isPlayerInput_Input interface {
	isPlayerInput_Input()
}

type PlayerInput_SimpleWiresInput struct {
	SimpleWiresInput *SimpleWiresInput `protobuf:"bytes,10,opt,name=simple_wires_input,json=simpleWiresInput,proto3,oneof"`
}

type PlayerInput_PasswordInput struct {
	PasswordInput *PasswordInput `protobuf:"bytes,11,opt,name=password_input,json=passwordInput,proto3,oneof"`
}

type PlayerInput_BigButtonInput struct {
	BigButtonInput *BigButtonInput `protobuf:"bytes,12,opt,name=big_button_input,json=bigButtonInput,proto3,oneof"`
}

type PlayerInput_SimonSaysInput struct {
	SimonSaysInput *SimonSaysInput `protobuf:"bytes,13,opt,name=simon_says_input,json=simonSaysInput,proto3,oneof"`
}

func (*PlayerInput_SimpleWiresInput) isPlayerInput_Input() {}

func (*PlayerInput_PasswordInput) isPlayerInput_Input() {}

func (*PlayerInput_BigButtonInput) isPlayerInput_Input() {}

func (*PlayerInput_SimonSaysInput) isPlayerInput_Input() {}

type PlayerInputResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ModuleId string                 `protobuf:"bytes,1,opt,name=module_id,json=moduleId,proto3" json:"module_id,omitempty"`
	Strike   bool                   `protobuf:"varint,2,opt,name=strike,proto3" json:"strike,omitempty"`
	Solved   bool                   `protobuf:"varint,3,opt,name=solved,proto3" json:"solved,omitempty"`
	// Types that are valid to be assigned to Result:
	//
	//	*PlayerInputResult_BigButtonInputResult
	//	*PlayerInputResult_SimonSaysInputResult
	Result        isPlayerInputResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInputResult) Reset() {
	*x = PlayerInputResult{}
	mi := &file_proto_player_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInputResult) ProtoMessage() {}

func (x *PlayerInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_player_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInputResult.ProtoReflect.Descriptor instead.
func (*PlayerInputResult) Descriptor() ([]byte, []int) {
	return file_proto_player_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerInputResult) GetModuleId() string {
	if x != nil {
		return x.ModuleId
	}
	return ""
}

func (x *PlayerInputResult) GetStrike() bool {
	if x != nil {
		return x.Strike
	}
	return false
}

func (x *PlayerInputResult) GetSolved() bool {
	if x != nil {
		return x.Solved
	}
	return false
}

func (x *PlayerInputResult) GetResult() isPlayerInputResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *PlayerInputResult) GetBigButtonInputResult() *BigButtonInputResult {
	if x != nil {
		if x, ok := x.Result.(*PlayerInputResult_BigButtonInputResult); ok {
			return x.BigButtonInputResult
		}
	}
	return nil
}

func (x *PlayerInputResult) GetSimonSaysInputResult() *SimonSaysInputResult {
	if x != nil {
		if x, ok := x.Result.(*PlayerInputResult_SimonSaysInputResult); ok {
			return x.SimonSaysInputResult
		}
	}
	return nil
}

type isPlayerInputResult_Result interface {
	isPlayerInputResult_Result()
}

type PlayerInputResult_BigButtonInputResult struct {
	BigButtonInputResult *BigButtonInputResult `protobuf:"bytes,10,opt,name=big_button_input_result,json=bigButtonInputResult,proto3,oneof"`
}

type PlayerInputResult_SimonSaysInputResult struct {
	SimonSaysInputResult *SimonSaysInputResult `protobuf:"bytes,11,opt,name=simon_says_input_result,json=simonSaysInputResult,proto3,oneof"`
}

func (*PlayerInputResult_BigButtonInputResult) isPlayerInputResult_Result() {}

func (*PlayerInputResult_SimonSaysInputResult) isPlayerInputResult_Result() {}

var File_proto_player_proto protoreflect.FileDescriptor

const file_proto_player_proto_rawDesc = "" +
	"\n" +
	"\x12proto/player.proto\x12\x06player\x1a\x1fproto/simple_wires_module.proto\x1a\x1bproto/password_module.proto\x1a\x1dproto/big_button_module.proto\x1a\x1dproto/simon_says_module.proto\"\x13\n" +
	"\x11CreateGameRequest\"3\n" +
	"\x12CreateGameResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x81\x03\n" +
	"\vPlayerInput\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\abomb_id\x18\x02 \x01(\tR\x06bombId\x12\x1b\n" +
	"\tmodule_id\x18\x03 \x01(\tR\bmoduleId\x12I\n" +
	"\x12simple_wires_input\x18\n" +
	" \x01(\v2\x19.modules.SimpleWiresInputH\x00R\x10simpleWiresInput\x12?\n" +
	"\x0epassword_input\x18\v \x01(\v2\x16.modules.PasswordInputH\x00R\rpasswordInput\x12C\n" +
	"\x10big_button_input\x18\f \x01(\v2\x17.modules.BigButtonInputH\x00R\x0ebigButtonInput\x12C\n" +
	"\x10simon_says_input\x18\r \x01(\v2\x17.modules.SimonSaysInputH\x00R\x0esimonSaysInputB\a\n" +
	"\x05input\"\x9a\x02\n" +
	"\x11PlayerInputResult\x12\x1b\n" +
	"\tmodule_id\x18\x01 \x01(\tR\bmoduleId\x12\x16\n" +
	"\x06strike\x18\x02 \x01(\bR\x06strike\x12\x16\n" +
	"\x06solved\x18\x03 \x01(\bR\x06solved\x12V\n" +
	"\x17big_button_input_result\x18\n" +
	" \x01(\v2\x1d.modules.BigButtonInputResultH\x00R\x14bigButtonInputResult\x12V\n" +
	"\x17simon_says_input_result\x18\v \x01(\v2\x1d.modules.SimonSaysInputResultH\x00R\x14simonSaysInputResultB\b\n" +
	"\x06resultB\tZ\a./protob\x06proto3"

var (
	file_proto_player_proto_rawDescOnce sync.Once
	file_proto_player_proto_rawDescData []byte
)

func file_proto_player_proto_rawDescGZIP() []byte {
	file_proto_player_proto_rawDescOnce.Do(func() {
		file_proto_player_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_player_proto_rawDesc), len(file_proto_player_proto_rawDesc)))
	})
	return file_proto_player_proto_rawDescData
}

var file_proto_player_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_player_proto_goTypes = []any{
	(*CreateGameRequest)(nil),    // 0: player.CreateGameRequest
	(*CreateGameResponse)(nil),   // 1: player.CreateGameResponse
	(*PlayerInput)(nil),          // 2: player.PlayerInput
	(*PlayerInputResult)(nil),    // 3: player.PlayerInputResult
	(*SimpleWiresInput)(nil),     // 4: modules.SimpleWiresInput
	(*PasswordInput)(nil),        // 5: modules.PasswordInput
	(*BigButtonInput)(nil),       // 6: modules.BigButtonInput
	(*SimonSaysInput)(nil),       // 7: modules.SimonSaysInput
	(*BigButtonInputResult)(nil), // 8: modules.BigButtonInputResult
	(*SimonSaysInputResult)(nil), // 9: modules.SimonSaysInputResult
}
var file_proto_player_proto_depIdxs = []int32{
	4, // 0: player.PlayerInput.simple_wires_input:type_name -> modules.SimpleWiresInput
	5, // 1: player.PlayerInput.password_input:type_name -> modules.PasswordInput
	6, // 2: player.PlayerInput.big_button_input:type_name -> modules.BigButtonInput
	7, // 3: player.PlayerInput.simon_says_input:type_name -> modules.SimonSaysInput
	8, // 4: player.PlayerInputResult.big_button_input_result:type_name -> modules.BigButtonInputResult
	9, // 5: player.PlayerInputResult.simon_says_input_result:type_name -> modules.SimonSaysInputResult
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_player_proto_init() }
func file_proto_player_proto_init() {
	if File_proto_player_proto != nil {
		return
	}
	file_proto_simple_wires_module_proto_init()
	file_proto_password_module_proto_init()
	file_proto_big_button_module_proto_init()
	file_proto_simon_says_module_proto_init()
	file_proto_player_proto_msgTypes[2].OneofWrappers = []any{
		(*PlayerInput_SimpleWiresInput)(nil),
		(*PlayerInput_PasswordInput)(nil),
		(*PlayerInput_BigButtonInput)(nil),
		(*PlayerInput_SimonSaysInput)(nil),
	}
	file_proto_player_proto_msgTypes[3].OneofWrappers = []any{
		(*PlayerInputResult_BigButtonInputResult)(nil),
		(*PlayerInputResult_SimonSaysInputResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_player_proto_rawDesc), len(file_proto_player_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_player_proto_goTypes,
		DependencyIndexes: file_proto_player_proto_depIdxs,
		MessageInfos:      file_proto_player_proto_msgTypes,
	}.Build()
	File_proto_player_proto = out.File
	file_proto_player_proto_goTypes = nil
	file_proto_player_proto_depIdxs = nil
}
