// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: proto/simon_says_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimonSaysInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         Color                  `protobuf:"varint,1,opt,name=color,proto3,enum=common.Color" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimonSaysInput) Reset() {
	*x = SimonSaysInput{}
	mi := &file_proto_simon_says_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimonSaysInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimonSaysInput) ProtoMessage() {}

func (x *SimonSaysInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simon_says_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimonSaysInput.ProtoReflect.Descriptor instead.
func (*SimonSaysInput) Descriptor() ([]byte, []int) {
	return file_proto_simon_says_module_proto_rawDescGZIP(), []int{0}
}

func (x *SimonSaysInput) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_RED
}

type SimonSaysState struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentSequence []Color                `protobuf:"varint,1,rep,packed,name=current_sequence,json=currentSequence,proto3,enum=common.Color" json:"current_sequence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SimonSaysState) Reset() {
	*x = SimonSaysState{}
	mi := &file_proto_simon_says_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimonSaysState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimonSaysState) ProtoMessage() {}

func (x *SimonSaysState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simon_says_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimonSaysState.ProtoReflect.Descriptor instead.
func (*SimonSaysState) Descriptor() ([]byte, []int) {
	return file_proto_simon_says_module_proto_rawDescGZIP(), []int{1}
}

func (x *SimonSaysState) GetCurrentSequence() []Color {
	if x != nil {
		return x.CurrentSequence
	}
	return nil
}

type SimonSaysInputResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NextSequence  []Color                `protobuf:"varint,1,rep,packed,name=next_sequence,json=nextSequence,proto3,enum=common.Color" json:"next_sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimonSaysInputResult) Reset() {
	*x = SimonSaysInputResult{}
	mi := &file_proto_simon_says_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimonSaysInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimonSaysInputResult) ProtoMessage() {}

func (x *SimonSaysInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simon_says_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimonSaysInputResult.ProtoReflect.Descriptor instead.
func (*SimonSaysInputResult) Descriptor() ([]byte, []int) {
	return file_proto_simon_says_module_proto_rawDescGZIP(), []int{2}
}

func (x *SimonSaysInputResult) GetNextSequence() []Color {
	if x != nil {
		return x.NextSequence
	}
	return nil
}

var File_proto_simon_says_module_proto protoreflect.FileDescriptor

const file_proto_simon_says_module_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/simon_says_module.proto\x12\amodules\x1a\x12proto/common.proto\"5\n" +
	"\x0eSimonSaysInput\x12#\n" +
	"\x05color\x18\x01 \x01(\x0e2\r.common.ColorR\x05color\"J\n" +
	"\x0eSimonSaysState\x128\n" +
	"\x10current_sequence\x18\x01 \x03(\x0e2\r.common.ColorR\x0fcurrentSequence\"J\n" +
	"\x14SimonSaysInputResult\x122\n" +
	"\rnext_sequence\x18\x01 \x03(\x0e2\r.common.ColorR\fnextSequenceB\tZ\a./protob\x06proto3"

var (
	file_proto_simon_says_module_proto_rawDescOnce sync.Once
	file_proto_simon_says_module_proto_rawDescData []byte
)

func file_proto_simon_says_module_proto_rawDescGZIP() []byte {
	file_proto_simon_says_module_proto_rawDescOnce.Do(func() {
		file_proto_simon_says_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simon_says_module_proto_rawDesc), len(file_proto_simon_says_module_proto_rawDesc)))
	})
	return file_proto_simon_says_module_proto_rawDescData
}

var file_proto_simon_says_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_simon_says_module_proto_goTypes = []any{
	(*SimonSaysInput)(nil),       // 0: modules.SimonSaysInput
	(*SimonSaysState)(nil),       // 1: modules.SimonSaysState
	(*SimonSaysInputResult)(nil), // 2: modules.SimonSaysInputResult
	(Color)(0),                   // 3: common.Color
}
var file_proto_simon_says_module_proto_depIdxs = []int32{
	3, // 0: modules.SimonSaysInput.color:type_name -> common.Color
	3, // 1: modules.SimonSaysState.current_sequence:type_name -> common.Color
	3, // 2: modules.SimonSaysInputResult.next_sequence:type_name -> common.Color
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_simon_says_module_proto_init() }
func file_proto_simon_says_module_proto_init() {
	if File_proto_simon_says_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simon_says_module_proto_rawDesc), len(file_proto_simon_says_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_simon_says_module_proto_goTypes,
		DependencyIndexes: file_proto_simon_says_module_proto_depIdxs,
		MessageInfos:      file_proto_simon_says_module_proto_msgTypes,
	}.Build()
	File_proto_simon_says_module_proto = out.File
	file_proto_simon_says_module_proto_goTypes = nil
	file_proto_simon_says_module_proto_depIdxs = nil
}
