// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.15.8
// source: proto/simple_wires_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleWiresInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireIndex     int32                  `protobuf:"varint,1,opt,name=wire_index,json=wireIndex,proto3" json:"wire_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleWiresInput) Reset() {
	*x = SimpleWiresInput{}
	mi := &file_proto_simple_wires_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleWiresInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleWiresInput) ProtoMessage() {}

func (x *SimpleWiresInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_wires_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleWiresInput.ProtoReflect.Descriptor instead.
func (*SimpleWiresInput) Descriptor() ([]byte, []int) {
	return file_proto_simple_wires_module_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleWiresInput) GetWireIndex() int32 {
	if x != nil {
		return x.WireIndex
	}
	return 0
}

type SimpleWiresState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wires         []*Wire                `protobuf:"bytes,1,rep,name=wires,proto3" json:"wires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleWiresState) Reset() {
	*x = SimpleWiresState{}
	mi := &file_proto_simple_wires_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleWiresState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleWiresState) ProtoMessage() {}

func (x *SimpleWiresState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_wires_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleWiresState.ProtoReflect.Descriptor instead.
func (*SimpleWiresState) Descriptor() ([]byte, []int) {
	return file_proto_simple_wires_module_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleWiresState) GetWires() []*Wire {
	if x != nil {
		return x.Wires
	}
	return nil
}

type Wire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireColor     string                 `protobuf:"bytes,1,opt,name=wire_color,json=wireColor,proto3" json:"wire_color,omitempty"`
	IsCut         bool                   `protobuf:"varint,2,opt,name=is_cut,json=isCut,proto3" json:"is_cut,omitempty"`
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wire) Reset() {
	*x = Wire{}
	mi := &file_proto_simple_wires_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wire) ProtoMessage() {}

func (x *Wire) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_wires_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wire.ProtoReflect.Descriptor instead.
func (*Wire) Descriptor() ([]byte, []int) {
	return file_proto_simple_wires_module_proto_rawDescGZIP(), []int{2}
}

func (x *Wire) GetWireColor() string {
	if x != nil {
		return x.WireColor
	}
	return ""
}

func (x *Wire) GetIsCut() bool {
	if x != nil {
		return x.IsCut
	}
	return false
}

func (x *Wire) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_proto_simple_wires_module_proto protoreflect.FileDescriptor

const file_proto_simple_wires_module_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/simple_wires_module.proto\x12\amodules\"1\n" +
	"\x10SimpleWiresInput\x12\x1d\n" +
	"\n" +
	"wire_index\x18\x01 \x01(\x05R\twireIndex\"7\n" +
	"\x10SimpleWiresState\x12#\n" +
	"\x05wires\x18\x01 \x03(\v2\r.modules.WireR\x05wires\"R\n" +
	"\x04Wire\x12\x1d\n" +
	"\n" +
	"wire_color\x18\x01 \x01(\tR\twireColor\x12\x15\n" +
	"\x06is_cut\x18\x02 \x01(\bR\x05isCut\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05indexB\tZ\a./protob\x06proto3"

var (
	file_proto_simple_wires_module_proto_rawDescOnce sync.Once
	file_proto_simple_wires_module_proto_rawDescData []byte
)

func file_proto_simple_wires_module_proto_rawDescGZIP() []byte {
	file_proto_simple_wires_module_proto_rawDescOnce.Do(func() {
		file_proto_simple_wires_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simple_wires_module_proto_rawDesc), len(file_proto_simple_wires_module_proto_rawDesc)))
	})
	return file_proto_simple_wires_module_proto_rawDescData
}

var file_proto_simple_wires_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_simple_wires_module_proto_goTypes = []any{
	(*SimpleWiresInput)(nil), // 0: modules.SimpleWiresInput
	(*SimpleWiresState)(nil), // 1: modules.SimpleWiresState
	(*Wire)(nil),             // 2: modules.Wire
}
var file_proto_simple_wires_module_proto_depIdxs = []int32{
	2, // 0: modules.SimpleWiresState.wires:type_name -> modules.Wire
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_simple_wires_module_proto_init() }
func file_proto_simple_wires_module_proto_init() {
	if File_proto_simple_wires_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simple_wires_module_proto_rawDesc), len(file_proto_simple_wires_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_simple_wires_module_proto_goTypes,
		DependencyIndexes: file_proto_simple_wires_module_proto_depIdxs,
		MessageInfos:      file_proto_simple_wires_module_proto_msgTypes,
	}.Build()
	File_proto_simple_wires_module_proto = out.File
	file_proto_simple_wires_module_proto_goTypes = nil
	file_proto_simple_wires_module_proto_depIdxs = nil
}
