// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/simple_wires_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleWiresInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireIndex     int32                  `protobuf:"varint,1,opt,name=wire_index,json=wireIndex,proto3" json:"wire_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleWiresInput) Reset() {
	*x = SimpleWiresInput{}
	mi := &file_proto_simple_wires_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleWiresInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleWiresInput) ProtoMessage() {}

func (x *SimpleWiresInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_simple_wires_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleWiresInput.ProtoReflect.Descriptor instead.
func (*SimpleWiresInput) Descriptor() ([]byte, []int) {
	return file_proto_simple_wires_module_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleWiresInput) GetWireIndex() int32 {
	if x != nil {
		return x.WireIndex
	}
	return 0
}

var File_proto_simple_wires_module_proto protoreflect.FileDescriptor

const file_proto_simple_wires_module_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/simple_wires_module.proto\x12\amodules\"1\n" +
	"\x10SimpleWiresInput\x12\x1d\n" +
	"\n" +
	"wire_index\x18\x01 \x01(\x05R\twireIndexB\tZ\a./protob\x06proto3"

var (
	file_proto_simple_wires_module_proto_rawDescOnce sync.Once
	file_proto_simple_wires_module_proto_rawDescData []byte
)

func file_proto_simple_wires_module_proto_rawDescGZIP() []byte {
	file_proto_simple_wires_module_proto_rawDescOnce.Do(func() {
		file_proto_simple_wires_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_simple_wires_module_proto_rawDesc), len(file_proto_simple_wires_module_proto_rawDesc)))
	})
	return file_proto_simple_wires_module_proto_rawDescData
}

var file_proto_simple_wires_module_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_simple_wires_module_proto_goTypes = []any{
	(*SimpleWiresInput)(nil), // 0: modules.SimpleWiresInput
}
var file_proto_simple_wires_module_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_simple_wires_module_proto_init() }
func file_proto_simple_wires_module_proto_init() {
	if File_proto_simple_wires_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_simple_wires_module_proto_rawDesc), len(file_proto_simple_wires_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_simple_wires_module_proto_goTypes,
		DependencyIndexes: file_proto_simple_wires_module_proto_depIdxs,
		MessageInfos:      file_proto_simple_wires_module_proto_msgTypes,
	}.Build()
	File_proto_simple_wires_module_proto = out.File
	file_proto_simple_wires_module_proto_goTypes = nil
	file_proto_simple_wires_module_proto_depIdxs = nil
}
