// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/wires_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WiresInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WirePosition  int32                  `protobuf:"varint,1,opt,name=wire_position,json=wirePosition,proto3" json:"wire_position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WiresInput) Reset() {
	*x = WiresInput{}
	mi := &file_proto_wires_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WiresInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiresInput) ProtoMessage() {}

func (x *WiresInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wires_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiresInput.ProtoReflect.Descriptor instead.
func (*WiresInput) Descriptor() ([]byte, []int) {
	return file_proto_wires_module_proto_rawDescGZIP(), []int{0}
}

func (x *WiresInput) GetWirePosition() int32 {
	if x != nil {
		return x.WirePosition
	}
	return 0
}

type WiresState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wires         []*Wire                `protobuf:"bytes,1,rep,name=wires,proto3" json:"wires,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WiresState) Reset() {
	*x = WiresState{}
	mi := &file_proto_wires_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WiresState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WiresState) ProtoMessage() {}

func (x *WiresState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wires_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WiresState.ProtoReflect.Descriptor instead.
func (*WiresState) Descriptor() ([]byte, []int) {
	return file_proto_wires_module_proto_rawDescGZIP(), []int{1}
}

func (x *WiresState) GetWires() []*Wire {
	if x != nil {
		return x.Wires
	}
	return nil
}

type Wire struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WireColor     Color                  `protobuf:"varint,1,opt,name=wire_color,json=wireColor,proto3,enum=common.Color" json:"wire_color,omitempty"`
	IsCut         bool                   `protobuf:"varint,2,opt,name=is_cut,json=isCut,proto3" json:"is_cut,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wire) Reset() {
	*x = Wire{}
	mi := &file_proto_wires_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wire) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wire) ProtoMessage() {}

func (x *Wire) ProtoReflect() protoreflect.Message {
	mi := &file_proto_wires_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wire.ProtoReflect.Descriptor instead.
func (*Wire) Descriptor() ([]byte, []int) {
	return file_proto_wires_module_proto_rawDescGZIP(), []int{2}
}

func (x *Wire) GetWireColor() Color {
	if x != nil {
		return x.WireColor
	}
	return Color_RED
}

func (x *Wire) GetIsCut() bool {
	if x != nil {
		return x.IsCut
	}
	return false
}

func (x *Wire) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

var File_proto_wires_module_proto protoreflect.FileDescriptor

const file_proto_wires_module_proto_rawDesc = "" +
	"\n" +
	"\x18proto/wires_module.proto\x12\amodules\x1a\x12proto/common.proto\"1\n" +
	"\n" +
	"WiresInput\x12#\n" +
	"\rwire_position\x18\x01 \x01(\x05R\fwirePosition\"1\n" +
	"\n" +
	"WiresState\x12#\n" +
	"\x05wires\x18\x01 \x03(\v2\r.modules.WireR\x05wires\"g\n" +
	"\x04Wire\x12,\n" +
	"\n" +
	"wire_color\x18\x01 \x01(\x0e2\r.common.ColorR\twireColor\x12\x15\n" +
	"\x06is_cut\x18\x02 \x01(\bR\x05isCut\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bpositionB\tZ\a./protob\x06proto3"

var (
	file_proto_wires_module_proto_rawDescOnce sync.Once
	file_proto_wires_module_proto_rawDescData []byte
)

func file_proto_wires_module_proto_rawDescGZIP() []byte {
	file_proto_wires_module_proto_rawDescOnce.Do(func() {
		file_proto_wires_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_wires_module_proto_rawDesc), len(file_proto_wires_module_proto_rawDesc)))
	})
	return file_proto_wires_module_proto_rawDescData
}

var file_proto_wires_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_wires_module_proto_goTypes = []any{
	(*WiresInput)(nil), // 0: modules.WiresInput
	(*WiresState)(nil), // 1: modules.WiresState
	(*Wire)(nil),       // 2: modules.Wire
	(Color)(0),         // 3: common.Color
}
var file_proto_wires_module_proto_depIdxs = []int32{
	2, // 0: modules.WiresState.wires:type_name -> modules.Wire
	3, // 1: modules.Wire.wire_color:type_name -> common.Color
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_wires_module_proto_init() }
func file_proto_wires_module_proto_init() {
	if File_proto_wires_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_wires_module_proto_rawDesc), len(file_proto_wires_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_wires_module_proto_goTypes,
		DependencyIndexes: file_proto_wires_module_proto_depIdxs,
		MessageInfos:      file_proto_wires_module_proto_msgTypes,
	}.Build()
	File_proto_wires_module_proto = out.File
	file_proto_wires_module_proto_goTypes = nil
	file_proto_wires_module_proto_depIdxs = nil
}
