// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/game_config.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mission int32

const (
	Mission_MISSION_UNSPECIFIED Mission = 0
	// Section 1: Introduction
	Mission_THE_FIRST_BOMB Mission = 1
	// Section 2: The Basics
	Mission_SOMETHING_OLD_SOMETHING_NEW Mission = 2
	Mission_DOUBLE_YOUR_MONEY           Mission = 3
	Mission_ONE_STEP_UP                 Mission = 4
	Mission_PICK_UP_THE_PACE            Mission = 5
	// Section 3: Moderate
	Mission_A_HIDDEN_MESSAGE     Mission = 6
	Mission_SOMETHINGS_DIFFERENT Mission = 7
	Mission_ONE_GIANT_LEAP       Mission = 8
	Mission_FAIR_GAME            Mission = 9
	Mission_PICK_UP_THE_PACE_II  Mission = 10
	Mission_NO_ROOM_FOR_ERROR    Mission = 11
	Mission_EIGHT_MINUTES        Mission = 12
	// Section 4: Needy Modules
	Mission_A_SMALL_WRINKLE Mission = 13
	Mission_PAY_ATTENTION   Mission = 14
	Mission_THE_KNOB        Mission = 15
	Mission_MULTI_TASKER    Mission = 16
	// Section 5: Challenging
	Mission_WIRES_WIRES_EVERYWHERE  Mission = 17
	Mission_COMPUTER_HACKING        Mission = 18
	Mission_WHOS_ON_FIRST_CHALLENGE Mission = 19
	Mission_FIENDISH                Mission = 20
	Mission_PICK_UP_THE_PACE_III    Mission = 21
	Mission_ONE_WITH_EVERYTHING     Mission = 22
	// Section 6: Extreme
	Mission_PICK_UP_THE_PACE_IV Mission = 23
	Mission_JUGGLER             Mission = 24
	Mission_DOUBLE_TROUBLE      Mission = 25
	Mission_I_AM_HARDCORE       Mission = 26
	// Section 7: Exotic
	Mission_BLINKENLIGHTS    Mission = 27
	Mission_APPLIED_THEORY   Mission = 28
	Mission_A_MAZE_ING       Mission = 29
	Mission_SNIP_SNAP        Mission = 30
	Mission_RAINBOW_TABLE    Mission = 31
	Mission_BLINKENLIGHTS_II Mission = 32
)

// Enum value maps for Mission.
var (
	Mission_name = map[int32]string{
		0:  "MISSION_UNSPECIFIED",
		1:  "THE_FIRST_BOMB",
		2:  "SOMETHING_OLD_SOMETHING_NEW",
		3:  "DOUBLE_YOUR_MONEY",
		4:  "ONE_STEP_UP",
		5:  "PICK_UP_THE_PACE",
		6:  "A_HIDDEN_MESSAGE",
		7:  "SOMETHINGS_DIFFERENT",
		8:  "ONE_GIANT_LEAP",
		9:  "FAIR_GAME",
		10: "PICK_UP_THE_PACE_II",
		11: "NO_ROOM_FOR_ERROR",
		12: "EIGHT_MINUTES",
		13: "A_SMALL_WRINKLE",
		14: "PAY_ATTENTION",
		15: "THE_KNOB",
		16: "MULTI_TASKER",
		17: "WIRES_WIRES_EVERYWHERE",
		18: "COMPUTER_HACKING",
		19: "WHOS_ON_FIRST_CHALLENGE",
		20: "FIENDISH",
		21: "PICK_UP_THE_PACE_III",
		22: "ONE_WITH_EVERYTHING",
		23: "PICK_UP_THE_PACE_IV",
		24: "JUGGLER",
		25: "DOUBLE_TROUBLE",
		26: "I_AM_HARDCORE",
		27: "BLINKENLIGHTS",
		28: "APPLIED_THEORY",
		29: "A_MAZE_ING",
		30: "SNIP_SNAP",
		31: "RAINBOW_TABLE",
		32: "BLINKENLIGHTS_II",
	}
	Mission_value = map[string]int32{
		"MISSION_UNSPECIFIED":         0,
		"THE_FIRST_BOMB":              1,
		"SOMETHING_OLD_SOMETHING_NEW": 2,
		"DOUBLE_YOUR_MONEY":           3,
		"ONE_STEP_UP":                 4,
		"PICK_UP_THE_PACE":            5,
		"A_HIDDEN_MESSAGE":            6,
		"SOMETHINGS_DIFFERENT":        7,
		"ONE_GIANT_LEAP":              8,
		"FAIR_GAME":                   9,
		"PICK_UP_THE_PACE_II":         10,
		"NO_ROOM_FOR_ERROR":           11,
		"EIGHT_MINUTES":               12,
		"A_SMALL_WRINKLE":             13,
		"PAY_ATTENTION":               14,
		"THE_KNOB":                    15,
		"MULTI_TASKER":                16,
		"WIRES_WIRES_EVERYWHERE":      17,
		"COMPUTER_HACKING":            18,
		"WHOS_ON_FIRST_CHALLENGE":     19,
		"FIENDISH":                    20,
		"PICK_UP_THE_PACE_III":        21,
		"ONE_WITH_EVERYTHING":         22,
		"PICK_UP_THE_PACE_IV":         23,
		"JUGGLER":                     24,
		"DOUBLE_TROUBLE":              25,
		"I_AM_HARDCORE":               26,
		"BLINKENLIGHTS":               27,
		"APPLIED_THEORY":              28,
		"A_MAZE_ING":                  29,
		"SNIP_SNAP":                   30,
		"RAINBOW_TABLE":               31,
		"BLINKENLIGHTS_II":            32,
	}
)

func (x Mission) Enum() *Mission {
	p := new(Mission)
	*p = x
	return p
}

func (x Mission) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mission) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_game_config_proto_enumTypes[0].Descriptor()
}

func (Mission) Type() protoreflect.EnumType {
	return &file_proto_game_config_proto_enumTypes[0]
}

func (x Mission) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mission.Descriptor instead.
func (Mission) EnumDescriptor() ([]byte, []int) {
	return file_proto_game_config_proto_rawDescGZIP(), []int{0}
}

// Level configuration (1-10 difficulty)
type LevelConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         int32                  `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LevelConfig) Reset() {
	*x = LevelConfig{}
	mi := &file_proto_game_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LevelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LevelConfig) ProtoMessage() {}

func (x *LevelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LevelConfig.ProtoReflect.Descriptor instead.
func (*LevelConfig) Descriptor() ([]byte, []int) {
	return file_proto_game_config_proto_rawDescGZIP(), []int{0}
}

func (x *LevelConfig) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type PresetMissionConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mission       Mission                `protobuf:"varint,1,opt,name=mission,proto3,enum=game_config.Mission" json:"mission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetMissionConfig) Reset() {
	*x = PresetMissionConfig{}
	mi := &file_proto_game_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetMissionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetMissionConfig) ProtoMessage() {}

func (x *PresetMissionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetMissionConfig.ProtoReflect.Descriptor instead.
func (*PresetMissionConfig) Descriptor() ([]byte, []int) {
	return file_proto_game_config_proto_rawDescGZIP(), []int{1}
}

func (x *PresetMissionConfig) GetMission() Mission {
	if x != nil {
		return x.Mission
	}
	return Mission_MISSION_UNSPECIFIED
}

type ModuleSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Module_ModuleType      `protobuf:"varint,1,opt,name=type,proto3,enum=modules.Module_ModuleType" json:"type,omitempty"`
	PossibleTypes []Module_ModuleType    `protobuf:"varint,2,rep,packed,name=possible_types,json=possibleTypes,proto3,enum=modules.Module_ModuleType" json:"possible_types,omitempty"`
	Count         int32                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleSpec) Reset() {
	*x = ModuleSpec{}
	mi := &file_proto_game_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleSpec) ProtoMessage() {}

func (x *ModuleSpec) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleSpec.ProtoReflect.Descriptor instead.
func (*ModuleSpec) Descriptor() ([]byte, []int) {
	return file_proto_game_config_proto_rawDescGZIP(), []int{2}
}

func (x *ModuleSpec) GetType() Module_ModuleType {
	if x != nil {
		return x.Type
	}
	return Module_UNKNOWN
}

func (x *ModuleSpec) GetPossibleTypes() []Module_ModuleType {
	if x != nil {
		return x.PossibleTypes
	}
	return nil
}

func (x *ModuleSpec) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CustomBombConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time limit in seconds (min: 5, max: 3600)
	TimerSeconds int32 `protobuf:"varint,1,opt,name=timer_seconds,json=timerSeconds,proto3" json:"timer_seconds,omitempty"`
	// Strike configuration (min: 1, max: 10)
	MaxStrikes int32 `protobuf:"varint,2,opt,name=max_strikes,json=maxStrikes,proto3" json:"max_strikes,omitempty"`
	// Face configuration (min: 1, max: 10)
	NumFaces int32 `protobuf:"varint,3,opt,name=num_faces,json=numFaces,proto3" json:"num_faces,omitempty"`
	// Grid layout (rows: 1-4, columns: 1-5)
	Rows    int32 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	Columns int32 `protobuf:"varint,5,opt,name=columns,proto3" json:"columns,omitempty"`
	// Module specification - explicit list of modules
	// If empty, uses weighted random selection
	Modules []*ModuleSpec `protobuf:"bytes,6,rep,name=modules,proto3" json:"modules,omitempty"`
	// Alternative: weighted random selection
	// Only used if modules list is empty
	MinModules        int32 `protobuf:"varint,7,opt,name=min_modules,json=minModules,proto3" json:"min_modules,omitempty"` // min: 1, max: 60
	MaxModulesPerFace int32 `protobuf:"varint,8,opt,name=max_modules_per_face,json=maxModulesPerFace,proto3" json:"max_modules_per_face,omitempty"`
	MinBatteries      int32 `protobuf:"varint,10,opt,name=min_batteries,json=minBatteries,proto3" json:"min_batteries,omitempty"`                  // 0-6
	MaxBatteries      int32 `protobuf:"varint,11,opt,name=max_batteries,json=maxBatteries,proto3" json:"max_batteries,omitempty"`                  // 0-6
	MaxIndicatorCount int32 `protobuf:"varint,12,opt,name=max_indicator_count,json=maxIndicatorCount,proto3" json:"max_indicator_count,omitempty"` // 0-5
	PortCount         int32 `protobuf:"varint,13,opt,name=port_count,json=portCount,proto3" json:"port_count,omitempty"`                           // 0-6
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CustomBombConfig) Reset() {
	*x = CustomBombConfig{}
	mi := &file_proto_game_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomBombConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomBombConfig) ProtoMessage() {}

func (x *CustomBombConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomBombConfig.ProtoReflect.Descriptor instead.
func (*CustomBombConfig) Descriptor() ([]byte, []int) {
	return file_proto_game_config_proto_rawDescGZIP(), []int{3}
}

func (x *CustomBombConfig) GetTimerSeconds() int32 {
	if x != nil {
		return x.TimerSeconds
	}
	return 0
}

func (x *CustomBombConfig) GetMaxStrikes() int32 {
	if x != nil {
		return x.MaxStrikes
	}
	return 0
}

func (x *CustomBombConfig) GetNumFaces() int32 {
	if x != nil {
		return x.NumFaces
	}
	return 0
}

func (x *CustomBombConfig) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *CustomBombConfig) GetColumns() int32 {
	if x != nil {
		return x.Columns
	}
	return 0
}

func (x *CustomBombConfig) GetModules() []*ModuleSpec {
	if x != nil {
		return x.Modules
	}
	return nil
}

func (x *CustomBombConfig) GetMinModules() int32 {
	if x != nil {
		return x.MinModules
	}
	return 0
}

func (x *CustomBombConfig) GetMaxModulesPerFace() int32 {
	if x != nil {
		return x.MaxModulesPerFace
	}
	return 0
}

func (x *CustomBombConfig) GetMinBatteries() int32 {
	if x != nil {
		return x.MinBatteries
	}
	return 0
}

func (x *CustomBombConfig) GetMaxBatteries() int32 {
	if x != nil {
		return x.MaxBatteries
	}
	return 0
}

func (x *CustomBombConfig) GetMaxIndicatorCount() int32 {
	if x != nil {
		return x.MaxIndicatorCount
	}
	return 0
}

func (x *CustomBombConfig) GetPortCount() int32 {
	if x != nil {
		return x.PortCount
	}
	return 0
}

type GameConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to ConfigType:
	//
	//	*GameConfig_Level
	//	*GameConfig_Preset
	//	*GameConfig_Custom
	ConfigType isGameConfig_ConfigType `protobuf_oneof:"config_type"`
	// Optional seed
	Seed          string `protobuf:"bytes,10,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameConfig) Reset() {
	*x = GameConfig{}
	mi := &file_proto_game_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameConfig) ProtoMessage() {}

func (x *GameConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameConfig.ProtoReflect.Descriptor instead.
func (*GameConfig) Descriptor() ([]byte, []int) {
	return file_proto_game_config_proto_rawDescGZIP(), []int{4}
}

func (x *GameConfig) GetConfigType() isGameConfig_ConfigType {
	if x != nil {
		return x.ConfigType
	}
	return nil
}

func (x *GameConfig) GetLevel() *LevelConfig {
	if x != nil {
		if x, ok := x.ConfigType.(*GameConfig_Level); ok {
			return x.Level
		}
	}
	return nil
}

func (x *GameConfig) GetPreset() *PresetMissionConfig {
	if x != nil {
		if x, ok := x.ConfigType.(*GameConfig_Preset); ok {
			return x.Preset
		}
	}
	return nil
}

func (x *GameConfig) GetCustom() *CustomBombConfig {
	if x != nil {
		if x, ok := x.ConfigType.(*GameConfig_Custom); ok {
			return x.Custom
		}
	}
	return nil
}

func (x *GameConfig) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

type isGameConfig_ConfigType interface {
	isGameConfig_ConfigType()
}

type GameConfig_Level struct {
	Level *LevelConfig `protobuf:"bytes,1,opt,name=level,proto3,oneof"`
}

type GameConfig_Preset struct {
	Preset *PresetMissionConfig `protobuf:"bytes,2,opt,name=preset,proto3,oneof"`
}

type GameConfig_Custom struct {
	Custom *CustomBombConfig `protobuf:"bytes,3,opt,name=custom,proto3,oneof"`
}

func (*GameConfig_Level) isGameConfig_ConfigType() {}

func (*GameConfig_Preset) isGameConfig_ConfigType() {}

func (*GameConfig_Custom) isGameConfig_ConfigType() {}

// Information about the generated configuration
type GeneratedConfigInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimerSeconds  int32                  `protobuf:"varint,1,opt,name=timer_seconds,json=timerSeconds,proto3" json:"timer_seconds,omitempty"`
	MaxStrikes    int32                  `protobuf:"varint,2,opt,name=max_strikes,json=maxStrikes,proto3" json:"max_strikes,omitempty"`
	NumFaces      int32                  `protobuf:"varint,3,opt,name=num_faces,json=numFaces,proto3" json:"num_faces,omitempty"`
	TotalModules  int32                  `protobuf:"varint,4,opt,name=total_modules,json=totalModules,proto3" json:"total_modules,omitempty"`
	ModuleTypes   []Module_ModuleType    `protobuf:"varint,5,rep,packed,name=module_types,json=moduleTypes,proto3,enum=modules.Module_ModuleType" json:"module_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedConfigInfo) Reset() {
	*x = GeneratedConfigInfo{}
	mi := &file_proto_game_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedConfigInfo) ProtoMessage() {}

func (x *GeneratedConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_game_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedConfigInfo.ProtoReflect.Descriptor instead.
func (*GeneratedConfigInfo) Descriptor() ([]byte, []int) {
	return file_proto_game_config_proto_rawDescGZIP(), []int{5}
}

func (x *GeneratedConfigInfo) GetTimerSeconds() int32 {
	if x != nil {
		return x.TimerSeconds
	}
	return 0
}

func (x *GeneratedConfigInfo) GetMaxStrikes() int32 {
	if x != nil {
		return x.MaxStrikes
	}
	return 0
}

func (x *GeneratedConfigInfo) GetNumFaces() int32 {
	if x != nil {
		return x.NumFaces
	}
	return 0
}

func (x *GeneratedConfigInfo) GetTotalModules() int32 {
	if x != nil {
		return x.TotalModules
	}
	return 0
}

func (x *GeneratedConfigInfo) GetModuleTypes() []Module_ModuleType {
	if x != nil {
		return x.ModuleTypes
	}
	return nil
}

var File_proto_game_config_proto protoreflect.FileDescriptor

const file_proto_game_config_proto_rawDesc = "" +
	"\n" +
	"\x17proto/game_config.proto\x12\vgame_config\x1a\x13proto/modules.proto\"#\n" +
	"\vLevelConfig\x12\x14\n" +
	"\x05level\x18\x01 \x01(\x05R\x05level\"E\n" +
	"\x13PresetMissionConfig\x12.\n" +
	"\amission\x18\x01 \x01(\x0e2\x14.game_config.MissionR\amission\"\x95\x01\n" +
	"\n" +
	"ModuleSpec\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.modules.Module.ModuleTypeR\x04type\x12A\n" +
	"\x0epossible_types\x18\x02 \x03(\x0e2\x1a.modules.Module.ModuleTypeR\rpossibleTypes\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x05R\x05count\"\xc1\x03\n" +
	"\x10CustomBombConfig\x12#\n" +
	"\rtimer_seconds\x18\x01 \x01(\x05R\ftimerSeconds\x12\x1f\n" +
	"\vmax_strikes\x18\x02 \x01(\x05R\n" +
	"maxStrikes\x12\x1b\n" +
	"\tnum_faces\x18\x03 \x01(\x05R\bnumFaces\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\x05R\x04rows\x12\x18\n" +
	"\acolumns\x18\x05 \x01(\x05R\acolumns\x121\n" +
	"\amodules\x18\x06 \x03(\v2\x17.game_config.ModuleSpecR\amodules\x12\x1f\n" +
	"\vmin_modules\x18\a \x01(\x05R\n" +
	"minModules\x12/\n" +
	"\x14max_modules_per_face\x18\b \x01(\x05R\x11maxModulesPerFace\x12#\n" +
	"\rmin_batteries\x18\n" +
	" \x01(\x05R\fminBatteries\x12#\n" +
	"\rmax_batteries\x18\v \x01(\x05R\fmaxBatteries\x12.\n" +
	"\x13max_indicator_count\x18\f \x01(\x05R\x11maxIndicatorCount\x12\x1d\n" +
	"\n" +
	"port_count\x18\r \x01(\x05R\tportCount\"\xd6\x01\n" +
	"\n" +
	"GameConfig\x120\n" +
	"\x05level\x18\x01 \x01(\v2\x18.game_config.LevelConfigH\x00R\x05level\x12:\n" +
	"\x06preset\x18\x02 \x01(\v2 .game_config.PresetMissionConfigH\x00R\x06preset\x127\n" +
	"\x06custom\x18\x03 \x01(\v2\x1d.game_config.CustomBombConfigH\x00R\x06custom\x12\x12\n" +
	"\x04seed\x18\n" +
	" \x01(\tR\x04seedB\r\n" +
	"\vconfig_type\"\xdc\x01\n" +
	"\x13GeneratedConfigInfo\x12#\n" +
	"\rtimer_seconds\x18\x01 \x01(\x05R\ftimerSeconds\x12\x1f\n" +
	"\vmax_strikes\x18\x02 \x01(\x05R\n" +
	"maxStrikes\x12\x1b\n" +
	"\tnum_faces\x18\x03 \x01(\x05R\bnumFaces\x12#\n" +
	"\rtotal_modules\x18\x04 \x01(\x05R\ftotalModules\x12=\n" +
	"\fmodule_types\x18\x05 \x03(\x0e2\x1a.modules.Module.ModuleTypeR\vmoduleTypes*\xbf\x05\n" +
	"\aMission\x12\x17\n" +
	"\x13MISSION_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTHE_FIRST_BOMB\x10\x01\x12\x1f\n" +
	"\x1bSOMETHING_OLD_SOMETHING_NEW\x10\x02\x12\x15\n" +
	"\x11DOUBLE_YOUR_MONEY\x10\x03\x12\x0f\n" +
	"\vONE_STEP_UP\x10\x04\x12\x14\n" +
	"\x10PICK_UP_THE_PACE\x10\x05\x12\x14\n" +
	"\x10A_HIDDEN_MESSAGE\x10\x06\x12\x18\n" +
	"\x14SOMETHINGS_DIFFERENT\x10\a\x12\x12\n" +
	"\x0eONE_GIANT_LEAP\x10\b\x12\r\n" +
	"\tFAIR_GAME\x10\t\x12\x17\n" +
	"\x13PICK_UP_THE_PACE_II\x10\n" +
	"\x12\x15\n" +
	"\x11NO_ROOM_FOR_ERROR\x10\v\x12\x11\n" +
	"\rEIGHT_MINUTES\x10\f\x12\x13\n" +
	"\x0fA_SMALL_WRINKLE\x10\r\x12\x11\n" +
	"\rPAY_ATTENTION\x10\x0e\x12\f\n" +
	"\bTHE_KNOB\x10\x0f\x12\x10\n" +
	"\fMULTI_TASKER\x10\x10\x12\x1a\n" +
	"\x16WIRES_WIRES_EVERYWHERE\x10\x11\x12\x14\n" +
	"\x10COMPUTER_HACKING\x10\x12\x12\x1b\n" +
	"\x17WHOS_ON_FIRST_CHALLENGE\x10\x13\x12\f\n" +
	"\bFIENDISH\x10\x14\x12\x18\n" +
	"\x14PICK_UP_THE_PACE_III\x10\x15\x12\x17\n" +
	"\x13ONE_WITH_EVERYTHING\x10\x16\x12\x17\n" +
	"\x13PICK_UP_THE_PACE_IV\x10\x17\x12\v\n" +
	"\aJUGGLER\x10\x18\x12\x12\n" +
	"\x0eDOUBLE_TROUBLE\x10\x19\x12\x11\n" +
	"\rI_AM_HARDCORE\x10\x1a\x12\x11\n" +
	"\rBLINKENLIGHTS\x10\x1b\x12\x12\n" +
	"\x0eAPPLIED_THEORY\x10\x1c\x12\x0e\n" +
	"\n" +
	"A_MAZE_ING\x10\x1d\x12\r\n" +
	"\tSNIP_SNAP\x10\x1e\x12\x11\n" +
	"\rRAINBOW_TABLE\x10\x1f\x12\x14\n" +
	"\x10BLINKENLIGHTS_II\x10 B\tZ\a./protob\x06proto3"

var (
	file_proto_game_config_proto_rawDescOnce sync.Once
	file_proto_game_config_proto_rawDescData []byte
)

func file_proto_game_config_proto_rawDescGZIP() []byte {
	file_proto_game_config_proto_rawDescOnce.Do(func() {
		file_proto_game_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_game_config_proto_rawDesc), len(file_proto_game_config_proto_rawDesc)))
	})
	return file_proto_game_config_proto_rawDescData
}

var file_proto_game_config_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_game_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_game_config_proto_goTypes = []any{
	(Mission)(0),                // 0: game_config.Mission
	(*LevelConfig)(nil),         // 1: game_config.LevelConfig
	(*PresetMissionConfig)(nil), // 2: game_config.PresetMissionConfig
	(*ModuleSpec)(nil),          // 3: game_config.ModuleSpec
	(*CustomBombConfig)(nil),    // 4: game_config.CustomBombConfig
	(*GameConfig)(nil),          // 5: game_config.GameConfig
	(*GeneratedConfigInfo)(nil), // 6: game_config.GeneratedConfigInfo
	(Module_ModuleType)(0),      // 7: modules.Module.ModuleType
}
var file_proto_game_config_proto_depIdxs = []int32{
	0, // 0: game_config.PresetMissionConfig.mission:type_name -> game_config.Mission
	7, // 1: game_config.ModuleSpec.type:type_name -> modules.Module.ModuleType
	7, // 2: game_config.ModuleSpec.possible_types:type_name -> modules.Module.ModuleType
	3, // 3: game_config.CustomBombConfig.modules:type_name -> game_config.ModuleSpec
	1, // 4: game_config.GameConfig.level:type_name -> game_config.LevelConfig
	2, // 5: game_config.GameConfig.preset:type_name -> game_config.PresetMissionConfig
	4, // 6: game_config.GameConfig.custom:type_name -> game_config.CustomBombConfig
	7, // 7: game_config.GeneratedConfigInfo.module_types:type_name -> modules.Module.ModuleType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_game_config_proto_init() }
func file_proto_game_config_proto_init() {
	if File_proto_game_config_proto != nil {
		return
	}
	file_proto_modules_proto_init()
	file_proto_game_config_proto_msgTypes[4].OneofWrappers = []any{
		(*GameConfig_Level)(nil),
		(*GameConfig_Preset)(nil),
		(*GameConfig_Custom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_config_proto_rawDesc), len(file_proto_game_config_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_game_config_proto_goTypes,
		DependencyIndexes: file_proto_game_config_proto_depIdxs,
		EnumInfos:         file_proto_game_config_proto_enumTypes,
		MessageInfos:      file_proto_game_config_proto_msgTypes,
	}.Build()
	File_proto_game_config_proto = out.File
	file_proto_game_config_proto_goTypes = nil
	file_proto_game_config_proto_depIdxs = nil
}
