// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/game.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_proto_game_proto protoreflect.FileDescriptor

const file_proto_game_proto_rawDesc = "" +
	"\n" +
	"\x10proto/game.proto\x12\x04game\x1a\x12proto/player.proto\x1a\x13proto/session.proto\x1a\x1cgoogle/api/annotations.proto2\x9f\x02\n" +
	"\vGameService\x12_\n" +
	"\n" +
	"CreateGame\x12\x19.player.CreateGameRequest\x1a\x1a.player.CreateGameResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/game/create\x12W\n" +
	"\bGetBombs\x12\x18.session.GetBombsRequest\x1a\x19.session.GetBombsResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/game/bombs\x12V\n" +
	"\tSendInput\x12\x13.player.PlayerInput\x1a\x19.player.PlayerInputResult\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/game/inputB\tZ\a./protob\x06proto3"

var file_proto_game_proto_goTypes = []any{
	(*CreateGameRequest)(nil),  // 0: player.CreateGameRequest
	(*GetBombsRequest)(nil),    // 1: session.GetBombsRequest
	(*PlayerInput)(nil),        // 2: player.PlayerInput
	(*CreateGameResponse)(nil), // 3: player.CreateGameResponse
	(*GetBombsResponse)(nil),   // 4: session.GetBombsResponse
	(*PlayerInputResult)(nil),  // 5: player.PlayerInputResult
}
var file_proto_game_proto_depIdxs = []int32{
	0, // 0: game.GameService.CreateGame:input_type -> player.CreateGameRequest
	1, // 1: game.GameService.GetBombs:input_type -> session.GetBombsRequest
	2, // 2: game.GameService.SendInput:input_type -> player.PlayerInput
	3, // 3: game.GameService.CreateGame:output_type -> player.CreateGameResponse
	4, // 4: game.GameService.GetBombs:output_type -> session.GetBombsResponse
	5, // 5: game.GameService.SendInput:output_type -> player.PlayerInputResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_game_proto_init() }
func file_proto_game_proto_init() {
	if File_proto_game_proto != nil {
		return
	}
	file_proto_player_proto_init()
	file_proto_session_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_game_proto_rawDesc), len(file_proto_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_game_proto_goTypes,
		DependencyIndexes: file_proto_game_proto_depIdxs,
	}.Build()
	File_proto_game_proto = out.File
	file_proto_game_proto_goTypes = nil
	file_proto_game_proto_depIdxs = nil
}
