// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/keypad_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Symbol int32

const (
	Symbol_COPYRIGHT  Symbol = 0
	Symbol_FILLEDSTAR Symbol = 1
	Symbol_HOLLOWSTAR Symbol = 2
	Symbol_SMILEYFACE Symbol = 3
	Symbol_DOUBLEK    Symbol = 4
	Symbol_OMEGA      Symbol = 5
	Symbol_SQUIDKNIFE Symbol = 6
	Symbol_PUMPKIN    Symbol = 7
	Symbol_HOOKN      Symbol = 8
	// TEEPEE = 9;
	Symbol_SIX         Symbol = 10
	Symbol_SQUIGGLYN   Symbol = 11
	Symbol_AT          Symbol = 12
	Symbol_AE          Symbol = 13
	Symbol_MELTEDTHREE Symbol = 14
	Symbol_EURO        Symbol = 15
	// CIRCLE = 16;
	Symbol_NWITHHAT     Symbol = 17
	Symbol_DRAGON       Symbol = 18
	Symbol_QUESTIONMARK Symbol = 19
	Symbol_PARAGRAPH    Symbol = 20
	Symbol_RIGHTC       Symbol = 21
	Symbol_LEFTC        Symbol = 22
	Symbol_PITCHFORK    Symbol = 23
	// TRIPOD = 24;
	Symbol_CURSIVE Symbol = 25
	Symbol_TRACKS  Symbol = 26
	Symbol_BALLOON Symbol = 27
	// WEIRDNOSE = 28;
	Symbol_UPSIDEDOWNY Symbol = 29
	Symbol_BT          Symbol = 30
)

// Enum value maps for Symbol.
var (
	Symbol_name = map[int32]string{
		0:  "COPYRIGHT",
		1:  "FILLEDSTAR",
		2:  "HOLLOWSTAR",
		3:  "SMILEYFACE",
		4:  "DOUBLEK",
		5:  "OMEGA",
		6:  "SQUIDKNIFE",
		7:  "PUMPKIN",
		8:  "HOOKN",
		10: "SIX",
		11: "SQUIGGLYN",
		12: "AT",
		13: "AE",
		14: "MELTEDTHREE",
		15: "EURO",
		17: "NWITHHAT",
		18: "DRAGON",
		19: "QUESTIONMARK",
		20: "PARAGRAPH",
		21: "RIGHTC",
		22: "LEFTC",
		23: "PITCHFORK",
		25: "CURSIVE",
		26: "TRACKS",
		27: "BALLOON",
		29: "UPSIDEDOWNY",
		30: "BT",
	}
	Symbol_value = map[string]int32{
		"COPYRIGHT":    0,
		"FILLEDSTAR":   1,
		"HOLLOWSTAR":   2,
		"SMILEYFACE":   3,
		"DOUBLEK":      4,
		"OMEGA":        5,
		"SQUIDKNIFE":   6,
		"PUMPKIN":      7,
		"HOOKN":        8,
		"SIX":          10,
		"SQUIGGLYN":    11,
		"AT":           12,
		"AE":           13,
		"MELTEDTHREE":  14,
		"EURO":         15,
		"NWITHHAT":     17,
		"DRAGON":       18,
		"QUESTIONMARK": 19,
		"PARAGRAPH":    20,
		"RIGHTC":       21,
		"LEFTC":        22,
		"PITCHFORK":    23,
		"CURSIVE":      25,
		"TRACKS":       26,
		"BALLOON":      27,
		"UPSIDEDOWNY":  29,
		"BT":           30,
	}
)

func (x Symbol) Enum() *Symbol {
	p := new(Symbol)
	*p = x
	return p
}

func (x Symbol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Symbol) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_keypad_module_proto_enumTypes[0].Descriptor()
}

func (Symbol) Type() protoreflect.EnumType {
	return &file_proto_keypad_module_proto_enumTypes[0]
}

func (x Symbol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Symbol.Descriptor instead.
func (Symbol) EnumDescriptor() ([]byte, []int) {
	return file_proto_keypad_module_proto_rawDescGZIP(), []int{0}
}

type KeypadInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        Symbol                 `protobuf:"varint,1,opt,name=symbol,proto3,enum=modules.Symbol" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeypadInput) Reset() {
	*x = KeypadInput{}
	mi := &file_proto_keypad_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeypadInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeypadInput) ProtoMessage() {}

func (x *KeypadInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keypad_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeypadInput.ProtoReflect.Descriptor instead.
func (*KeypadInput) Descriptor() ([]byte, []int) {
	return file_proto_keypad_module_proto_rawDescGZIP(), []int{0}
}

func (x *KeypadInput) GetSymbol() Symbol {
	if x != nil {
		return x.Symbol
	}
	return Symbol_COPYRIGHT
}

type KeypadInputResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeypadState   *KeypadState           `protobuf:"bytes,1,opt,name=keypad_state,json=keypadState,proto3" json:"keypad_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeypadInputResult) Reset() {
	*x = KeypadInputResult{}
	mi := &file_proto_keypad_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeypadInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeypadInputResult) ProtoMessage() {}

func (x *KeypadInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keypad_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeypadInputResult.ProtoReflect.Descriptor instead.
func (*KeypadInputResult) Descriptor() ([]byte, []int) {
	return file_proto_keypad_module_proto_rawDescGZIP(), []int{1}
}

func (x *KeypadInputResult) GetKeypadState() *KeypadState {
	if x != nil {
		return x.KeypadState
	}
	return nil
}

type KeypadState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DisplayedSymbols []Symbol               `protobuf:"varint,1,rep,packed,name=displayed_symbols,json=displayedSymbols,proto3,enum=modules.Symbol" json:"displayed_symbols,omitempty"`
	ActivatedSymbols []Symbol               `protobuf:"varint,2,rep,packed,name=activated_symbols,json=activatedSymbols,proto3,enum=modules.Symbol" json:"activated_symbols,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeypadState) Reset() {
	*x = KeypadState{}
	mi := &file_proto_keypad_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeypadState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeypadState) ProtoMessage() {}

func (x *KeypadState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_keypad_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeypadState.ProtoReflect.Descriptor instead.
func (*KeypadState) Descriptor() ([]byte, []int) {
	return file_proto_keypad_module_proto_rawDescGZIP(), []int{2}
}

func (x *KeypadState) GetDisplayedSymbols() []Symbol {
	if x != nil {
		return x.DisplayedSymbols
	}
	return nil
}

func (x *KeypadState) GetActivatedSymbols() []Symbol {
	if x != nil {
		return x.ActivatedSymbols
	}
	return nil
}

var File_proto_keypad_module_proto protoreflect.FileDescriptor

const file_proto_keypad_module_proto_rawDesc = "" +
	"\n" +
	"\x19proto/keypad_module.proto\x12\amodules\x1a\x12proto/common.proto\"6\n" +
	"\vKeypadInput\x12'\n" +
	"\x06symbol\x18\x01 \x01(\x0e2\x0f.modules.SymbolR\x06symbol\"L\n" +
	"\x11KeypadInputResult\x127\n" +
	"\fkeypad_state\x18\x01 \x01(\v2\x14.modules.KeypadStateR\vkeypadState\"\x89\x01\n" +
	"\vKeypadState\x12<\n" +
	"\x11displayed_symbols\x18\x01 \x03(\x0e2\x0f.modules.SymbolR\x10displayedSymbols\x12<\n" +
	"\x11activated_symbols\x18\x02 \x03(\x0e2\x0f.modules.SymbolR\x10activatedSymbols*\xea\x02\n" +
	"\x06Symbol\x12\r\n" +
	"\tCOPYRIGHT\x10\x00\x12\x0e\n" +
	"\n" +
	"FILLEDSTAR\x10\x01\x12\x0e\n" +
	"\n" +
	"HOLLOWSTAR\x10\x02\x12\x0e\n" +
	"\n" +
	"SMILEYFACE\x10\x03\x12\v\n" +
	"\aDOUBLEK\x10\x04\x12\t\n" +
	"\x05OMEGA\x10\x05\x12\x0e\n" +
	"\n" +
	"SQUIDKNIFE\x10\x06\x12\v\n" +
	"\aPUMPKIN\x10\a\x12\t\n" +
	"\x05HOOKN\x10\b\x12\a\n" +
	"\x03SIX\x10\n" +
	"\x12\r\n" +
	"\tSQUIGGLYN\x10\v\x12\x06\n" +
	"\x02AT\x10\f\x12\x06\n" +
	"\x02AE\x10\r\x12\x0f\n" +
	"\vMELTEDTHREE\x10\x0e\x12\b\n" +
	"\x04EURO\x10\x0f\x12\f\n" +
	"\bNWITHHAT\x10\x11\x12\n" +
	"\n" +
	"\x06DRAGON\x10\x12\x12\x10\n" +
	"\fQUESTIONMARK\x10\x13\x12\r\n" +
	"\tPARAGRAPH\x10\x14\x12\n" +
	"\n" +
	"\x06RIGHTC\x10\x15\x12\t\n" +
	"\x05LEFTC\x10\x16\x12\r\n" +
	"\tPITCHFORK\x10\x17\x12\v\n" +
	"\aCURSIVE\x10\x19\x12\n" +
	"\n" +
	"\x06TRACKS\x10\x1a\x12\v\n" +
	"\aBALLOON\x10\x1b\x12\x0f\n" +
	"\vUPSIDEDOWNY\x10\x1d\x12\x06\n" +
	"\x02BT\x10\x1eB\tZ\a./protob\x06proto3"

var (
	file_proto_keypad_module_proto_rawDescOnce sync.Once
	file_proto_keypad_module_proto_rawDescData []byte
)

func file_proto_keypad_module_proto_rawDescGZIP() []byte {
	file_proto_keypad_module_proto_rawDescOnce.Do(func() {
		file_proto_keypad_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_keypad_module_proto_rawDesc), len(file_proto_keypad_module_proto_rawDesc)))
	})
	return file_proto_keypad_module_proto_rawDescData
}

var file_proto_keypad_module_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_keypad_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_keypad_module_proto_goTypes = []any{
	(Symbol)(0),               // 0: modules.Symbol
	(*KeypadInput)(nil),       // 1: modules.KeypadInput
	(*KeypadInputResult)(nil), // 2: modules.KeypadInputResult
	(*KeypadState)(nil),       // 3: modules.KeypadState
}
var file_proto_keypad_module_proto_depIdxs = []int32{
	0, // 0: modules.KeypadInput.symbol:type_name -> modules.Symbol
	3, // 1: modules.KeypadInputResult.keypad_state:type_name -> modules.KeypadState
	0, // 2: modules.KeypadState.displayed_symbols:type_name -> modules.Symbol
	0, // 3: modules.KeypadState.activated_symbols:type_name -> modules.Symbol
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_keypad_module_proto_init() }
func file_proto_keypad_module_proto_init() {
	if File_proto_keypad_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_keypad_module_proto_rawDesc), len(file_proto_keypad_module_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_keypad_module_proto_goTypes,
		DependencyIndexes: file_proto_keypad_module_proto_depIdxs,
		EnumInfos:         file_proto_keypad_module_proto_enumTypes,
		MessageInfos:      file_proto_keypad_module_proto_msgTypes,
	}.Build()
	File_proto_keypad_module_proto = out.File
	file_proto_keypad_module_proto_goTypes = nil
	file_proto_keypad_module_proto_depIdxs = nil
}
