// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/memory_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ButtonIndex   int32                  `protobuf:"varint,1,opt,name=button_index,json=buttonIndex,proto3" json:"button_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInput) Reset() {
	*x = MemoryInput{}
	mi := &file_proto_memory_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInput) ProtoMessage() {}

func (x *MemoryInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInput.ProtoReflect.Descriptor instead.
func (*MemoryInput) Descriptor() ([]byte, []int) {
	return file_proto_memory_module_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryInput) GetButtonIndex() int32 {
	if x != nil {
		return x.ButtonIndex
	}
	return 0
}

type MemoryInputResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryState   *MemoryState           `protobuf:"bytes,1,opt,name=memory_state,json=memoryState,proto3" json:"memory_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryInputResult) Reset() {
	*x = MemoryInputResult{}
	mi := &file_proto_memory_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryInputResult) ProtoMessage() {}

func (x *MemoryInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryInputResult.ProtoReflect.Descriptor instead.
func (*MemoryInputResult) Descriptor() ([]byte, []int) {
	return file_proto_memory_module_proto_rawDescGZIP(), []int{1}
}

func (x *MemoryInputResult) GetMemoryState() *MemoryState {
	if x != nil {
		return x.MemoryState
	}
	return nil
}

type MemoryState struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ScreenNumber     int32                  `protobuf:"varint,1,opt,name=screen_number,json=screenNumber,proto3" json:"screen_number,omitempty"`
	DisplayedNumbers []int32                `protobuf:"varint,2,rep,packed,name=displayed_numbers,json=displayedNumbers,proto3" json:"displayed_numbers,omitempty"`
	Stage            int32                  `protobuf:"varint,3,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MemoryState) Reset() {
	*x = MemoryState{}
	mi := &file_proto_memory_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryState) ProtoMessage() {}

func (x *MemoryState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_memory_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryState.ProtoReflect.Descriptor instead.
func (*MemoryState) Descriptor() ([]byte, []int) {
	return file_proto_memory_module_proto_rawDescGZIP(), []int{2}
}

func (x *MemoryState) GetScreenNumber() int32 {
	if x != nil {
		return x.ScreenNumber
	}
	return 0
}

func (x *MemoryState) GetDisplayedNumbers() []int32 {
	if x != nil {
		return x.DisplayedNumbers
	}
	return nil
}

func (x *MemoryState) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

var File_proto_memory_module_proto protoreflect.FileDescriptor

const file_proto_memory_module_proto_rawDesc = "" +
	"\n" +
	"\x19proto/memory_module.proto\x12\amodules\x1a\x12proto/common.proto\"0\n" +
	"\vMemoryInput\x12!\n" +
	"\fbutton_index\x18\x01 \x01(\x05R\vbuttonIndex\"L\n" +
	"\x11MemoryInputResult\x127\n" +
	"\fmemory_state\x18\x01 \x01(\v2\x14.modules.MemoryStateR\vmemoryState\"u\n" +
	"\vMemoryState\x12#\n" +
	"\rscreen_number\x18\x01 \x01(\x05R\fscreenNumber\x12+\n" +
	"\x11displayed_numbers\x18\x02 \x03(\x05R\x10displayedNumbers\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\x05R\x05stageB\tZ\a./protob\x06proto3"

var (
	file_proto_memory_module_proto_rawDescOnce sync.Once
	file_proto_memory_module_proto_rawDescData []byte
)

func file_proto_memory_module_proto_rawDescGZIP() []byte {
	file_proto_memory_module_proto_rawDescOnce.Do(func() {
		file_proto_memory_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_memory_module_proto_rawDesc), len(file_proto_memory_module_proto_rawDesc)))
	})
	return file_proto_memory_module_proto_rawDescData
}

var file_proto_memory_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_memory_module_proto_goTypes = []any{
	(*MemoryInput)(nil),       // 0: modules.MemoryInput
	(*MemoryInputResult)(nil), // 1: modules.MemoryInputResult
	(*MemoryState)(nil),       // 2: modules.MemoryState
}
var file_proto_memory_module_proto_depIdxs = []int32{
	2, // 0: modules.MemoryInputResult.memory_state:type_name -> modules.MemoryState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_memory_module_proto_init() }
func file_proto_memory_module_proto_init() {
	if File_proto_memory_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_memory_module_proto_rawDesc), len(file_proto_memory_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_memory_module_proto_goTypes,
		DependencyIndexes: file_proto_memory_module_proto_depIdxs,
		MessageInfos:      file_proto_memory_module_proto_msgTypes,
	}.Build()
	File_proto_memory_module_proto = out.File
	file_proto_memory_module_proto_goTypes = nil
	file_proto_memory_module_proto_depIdxs = nil
}
