// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/modules.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Module_ModuleType int32

const (
	Module_UNKNOWN        Module_ModuleType = 0
	Module_CLOCK          Module_ModuleType = 1
	Module_WIRES          Module_ModuleType = 2
	Module_PASSWORD       Module_ModuleType = 3
	Module_BIG_BUTTON     Module_ModuleType = 4
	Module_SIMON          Module_ModuleType = 5
	Module_KEYPAD         Module_ModuleType = 6
	Module_WHOS_ON_FIRST  Module_ModuleType = 7
	Module_MEMORY         Module_ModuleType = 8
	Module_MORSE          Module_ModuleType = 9
	Module_NEEDY_VENT_GAS Module_ModuleType = 10
	Module_NEEDY_KNOB     Module_ModuleType = 11
	Module_MAZE           Module_ModuleType = 12
)

// Enum value maps for Module_ModuleType.
var (
	Module_ModuleType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "CLOCK",
		2:  "WIRES",
		3:  "PASSWORD",
		4:  "BIG_BUTTON",
		5:  "SIMON",
		6:  "KEYPAD",
		7:  "WHOS_ON_FIRST",
		8:  "MEMORY",
		9:  "MORSE",
		10: "NEEDY_VENT_GAS",
		11: "NEEDY_KNOB",
		12: "MAZE",
	}
	Module_ModuleType_value = map[string]int32{
		"UNKNOWN":        0,
		"CLOCK":          1,
		"WIRES":          2,
		"PASSWORD":       3,
		"BIG_BUTTON":     4,
		"SIMON":          5,
		"KEYPAD":         6,
		"WHOS_ON_FIRST":  7,
		"MEMORY":         8,
		"MORSE":          9,
		"NEEDY_VENT_GAS": 10,
		"NEEDY_KNOB":     11,
		"MAZE":           12,
	}
)

func (x Module_ModuleType) Enum() *Module_ModuleType {
	p := new(Module_ModuleType)
	*p = x
	return p
}

func (x Module_ModuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Module_ModuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_modules_proto_enumTypes[0].Descriptor()
}

func (Module_ModuleType) Type() protoreflect.EnumType {
	return &file_proto_modules_proto_enumTypes[0]
}

func (x Module_ModuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Module_ModuleType.Descriptor instead.
func (Module_ModuleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{1, 0}
}

type ModulePosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Face          int32                  `protobuf:"varint,1,opt,name=face,proto3" json:"face,omitempty"`
	Row           int32                  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,3,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModulePosition) Reset() {
	*x = ModulePosition{}
	mi := &file_proto_modules_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModulePosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModulePosition) ProtoMessage() {}

func (x *ModulePosition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModulePosition.ProtoReflect.Descriptor instead.
func (*ModulePosition) Descriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{0}
}

func (x *ModulePosition) GetFace() int32 {
	if x != nil {
		return x.Face
	}
	return 0
}

func (x *ModulePosition) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ModulePosition) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type Module struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type     Module_ModuleType      `protobuf:"varint,2,opt,name=type,proto3,enum=modules.Module_ModuleType" json:"type,omitempty"`
	Position *ModulePosition        `protobuf:"bytes,3,opt,name=position,proto3" json:"position,omitempty"`
	Solved   bool                   `protobuf:"varint,4,opt,name=solved,proto3" json:"solved,omitempty"`
	// Types that are valid to be assigned to State:
	//
	//	*Module_WiresState
	//	*Module_PasswordState
	//	*Module_BigButtonState
	//	*Module_SimonState
	//	*Module_KeypadState
	//	*Module_WhosOnFirstState
	//	*Module_MemoryState
	//	*Module_MorseState
	//	*Module_NeedyVentGasState
	//	*Module_NeedyKnobState
	//	*Module_MazeState
	State         isModule_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Module) Reset() {
	*x = Module{}
	mi := &file_proto_modules_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Module) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Module) ProtoMessage() {}

func (x *Module) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Module.ProtoReflect.Descriptor instead.
func (*Module) Descriptor() ([]byte, []int) {
	return file_proto_modules_proto_rawDescGZIP(), []int{1}
}

func (x *Module) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Module) GetType() Module_ModuleType {
	if x != nil {
		return x.Type
	}
	return Module_UNKNOWN
}

func (x *Module) GetPosition() *ModulePosition {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Module) GetSolved() bool {
	if x != nil {
		return x.Solved
	}
	return false
}

func (x *Module) GetState() isModule_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *Module) GetWiresState() *WiresState {
	if x != nil {
		if x, ok := x.State.(*Module_WiresState); ok {
			return x.WiresState
		}
	}
	return nil
}

func (x *Module) GetPasswordState() *PasswordState {
	if x != nil {
		if x, ok := x.State.(*Module_PasswordState); ok {
			return x.PasswordState
		}
	}
	return nil
}

func (x *Module) GetBigButtonState() *BigButtonState {
	if x != nil {
		if x, ok := x.State.(*Module_BigButtonState); ok {
			return x.BigButtonState
		}
	}
	return nil
}

func (x *Module) GetSimonState() *SimonState {
	if x != nil {
		if x, ok := x.State.(*Module_SimonState); ok {
			return x.SimonState
		}
	}
	return nil
}

func (x *Module) GetKeypadState() *KeypadState {
	if x != nil {
		if x, ok := x.State.(*Module_KeypadState); ok {
			return x.KeypadState
		}
	}
	return nil
}

func (x *Module) GetWhosOnFirstState() *WhosOnFirstState {
	if x != nil {
		if x, ok := x.State.(*Module_WhosOnFirstState); ok {
			return x.WhosOnFirstState
		}
	}
	return nil
}

func (x *Module) GetMemoryState() *MemoryState {
	if x != nil {
		if x, ok := x.State.(*Module_MemoryState); ok {
			return x.MemoryState
		}
	}
	return nil
}

func (x *Module) GetMorseState() *MorseState {
	if x != nil {
		if x, ok := x.State.(*Module_MorseState); ok {
			return x.MorseState
		}
	}
	return nil
}

func (x *Module) GetNeedyVentGasState() *NeedyVentGasState {
	if x != nil {
		if x, ok := x.State.(*Module_NeedyVentGasState); ok {
			return x.NeedyVentGasState
		}
	}
	return nil
}

func (x *Module) GetNeedyKnobState() *NeedyKnobState {
	if x != nil {
		if x, ok := x.State.(*Module_NeedyKnobState); ok {
			return x.NeedyKnobState
		}
	}
	return nil
}

func (x *Module) GetMazeState() *MazeState {
	if x != nil {
		if x, ok := x.State.(*Module_MazeState); ok {
			return x.MazeState
		}
	}
	return nil
}

type isModule_State interface {
	isModule_State()
}

type Module_WiresState struct {
	WiresState *WiresState `protobuf:"bytes,5,opt,name=wires_state,json=wiresState,proto3,oneof"`
}

type Module_PasswordState struct {
	PasswordState *PasswordState `protobuf:"bytes,6,opt,name=password_state,json=passwordState,proto3,oneof"`
}

type Module_BigButtonState struct {
	BigButtonState *BigButtonState `protobuf:"bytes,7,opt,name=big_button_state,json=bigButtonState,proto3,oneof"`
}

type Module_SimonState struct {
	SimonState *SimonState `protobuf:"bytes,8,opt,name=simon_state,json=simonState,proto3,oneof"`
}

type Module_KeypadState struct {
	KeypadState *KeypadState `protobuf:"bytes,9,opt,name=keypad_state,json=keypadState,proto3,oneof"`
}

type Module_WhosOnFirstState struct {
	WhosOnFirstState *WhosOnFirstState `protobuf:"bytes,10,opt,name=whos_on_first_state,json=whosOnFirstState,proto3,oneof"`
}

type Module_MemoryState struct {
	MemoryState *MemoryState `protobuf:"bytes,11,opt,name=memory_state,json=memoryState,proto3,oneof"`
}

type Module_MorseState struct {
	MorseState *MorseState `protobuf:"bytes,12,opt,name=morse_state,json=morseState,proto3,oneof"`
}

type Module_NeedyVentGasState struct {
	NeedyVentGasState *NeedyVentGasState `protobuf:"bytes,13,opt,name=needy_vent_gas_state,json=needyVentGasState,proto3,oneof"`
}

type Module_NeedyKnobState struct {
	NeedyKnobState *NeedyKnobState `protobuf:"bytes,14,opt,name=needy_knob_state,json=needyKnobState,proto3,oneof"`
}

type Module_MazeState struct {
	MazeState *MazeState `protobuf:"bytes,15,opt,name=maze_state,json=mazeState,proto3,oneof"`
}

func (*Module_WiresState) isModule_State() {}

func (*Module_PasswordState) isModule_State() {}

func (*Module_BigButtonState) isModule_State() {}

func (*Module_SimonState) isModule_State() {}

func (*Module_KeypadState) isModule_State() {}

func (*Module_WhosOnFirstState) isModule_State() {}

func (*Module_MemoryState) isModule_State() {}

func (*Module_MorseState) isModule_State() {}

func (*Module_NeedyVentGasState) isModule_State() {}

func (*Module_NeedyKnobState) isModule_State() {}

func (*Module_MazeState) isModule_State() {}

var File_proto_modules_proto protoreflect.FileDescriptor

const file_proto_modules_proto_rawDesc = "" +
	"\n" +
	"\x13proto/modules.proto\x12\amodules\x1a\x18proto/wires_module.proto\x1a\x1dproto/big_button_module.proto\x1a\x18proto/simon_module.proto\x1a\x1bproto/password_module.proto\x1a\x19proto/keypad_module.proto\x1a proto/whos_on_first_module.proto\x1a\x19proto/memory_module.proto\x1a\x18proto/morse_module.proto\x1a!proto/needy_vent_gas_module.proto\x1a\x1dproto/needy_knob_module.proto\x1a\x17proto/maze_module.proto\"H\n" +
	"\x0eModulePosition\x12\x12\n" +
	"\x04face\x18\x01 \x01(\x05R\x04face\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x03 \x01(\x05R\x03col\"\x96\b\n" +
	"\x06Module\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1a.modules.Module.ModuleTypeR\x04type\x123\n" +
	"\bposition\x18\x03 \x01(\v2\x17.modules.ModulePositionR\bposition\x12\x16\n" +
	"\x06solved\x18\x04 \x01(\bR\x06solved\x126\n" +
	"\vwires_state\x18\x05 \x01(\v2\x13.modules.WiresStateH\x00R\n" +
	"wiresState\x12?\n" +
	"\x0epassword_state\x18\x06 \x01(\v2\x16.modules.PasswordStateH\x00R\rpasswordState\x12C\n" +
	"\x10big_button_state\x18\a \x01(\v2\x17.modules.BigButtonStateH\x00R\x0ebigButtonState\x126\n" +
	"\vsimon_state\x18\b \x01(\v2\x13.modules.SimonStateH\x00R\n" +
	"simonState\x129\n" +
	"\fkeypad_state\x18\t \x01(\v2\x14.modules.KeypadStateH\x00R\vkeypadState\x12J\n" +
	"\x13whos_on_first_state\x18\n" +
	" \x01(\v2\x19.modules.WhosOnFirstStateH\x00R\x10whosOnFirstState\x129\n" +
	"\fmemory_state\x18\v \x01(\v2\x14.modules.MemoryStateH\x00R\vmemoryState\x126\n" +
	"\vmorse_state\x18\f \x01(\v2\x13.modules.MorseStateH\x00R\n" +
	"morseState\x12M\n" +
	"\x14needy_vent_gas_state\x18\r \x01(\v2\x1a.modules.NeedyVentGasStateH\x00R\x11needyVentGasState\x12C\n" +
	"\x10needy_knob_state\x18\x0e \x01(\v2\x17.modules.NeedyKnobStateH\x00R\x0eneedyKnobState\x123\n" +
	"\n" +
	"maze_state\x18\x0f \x01(\v2\x12.modules.MazeStateH\x00R\tmazeState\"\xbc\x01\n" +
	"\n" +
	"ModuleType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\t\n" +
	"\x05CLOCK\x10\x01\x12\t\n" +
	"\x05WIRES\x10\x02\x12\f\n" +
	"\bPASSWORD\x10\x03\x12\x0e\n" +
	"\n" +
	"BIG_BUTTON\x10\x04\x12\t\n" +
	"\x05SIMON\x10\x05\x12\n" +
	"\n" +
	"\x06KEYPAD\x10\x06\x12\x11\n" +
	"\rWHOS_ON_FIRST\x10\a\x12\n" +
	"\n" +
	"\x06MEMORY\x10\b\x12\t\n" +
	"\x05MORSE\x10\t\x12\x12\n" +
	"\x0eNEEDY_VENT_GAS\x10\n" +
	"\x12\x0e\n" +
	"\n" +
	"NEEDY_KNOB\x10\v\x12\b\n" +
	"\x04MAZE\x10\fB\a\n" +
	"\x05stateB\tZ\a./protob\x06proto3"

var (
	file_proto_modules_proto_rawDescOnce sync.Once
	file_proto_modules_proto_rawDescData []byte
)

func file_proto_modules_proto_rawDescGZIP() []byte {
	file_proto_modules_proto_rawDescOnce.Do(func() {
		file_proto_modules_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_modules_proto_rawDesc), len(file_proto_modules_proto_rawDesc)))
	})
	return file_proto_modules_proto_rawDescData
}

var file_proto_modules_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_modules_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_modules_proto_goTypes = []any{
	(Module_ModuleType)(0),    // 0: modules.Module.ModuleType
	(*ModulePosition)(nil),    // 1: modules.ModulePosition
	(*Module)(nil),            // 2: modules.Module
	(*WiresState)(nil),        // 3: modules.WiresState
	(*PasswordState)(nil),     // 4: modules.PasswordState
	(*BigButtonState)(nil),    // 5: modules.BigButtonState
	(*SimonState)(nil),        // 6: modules.SimonState
	(*KeypadState)(nil),       // 7: modules.KeypadState
	(*WhosOnFirstState)(nil),  // 8: modules.WhosOnFirstState
	(*MemoryState)(nil),       // 9: modules.MemoryState
	(*MorseState)(nil),        // 10: modules.MorseState
	(*NeedyVentGasState)(nil), // 11: modules.NeedyVentGasState
	(*NeedyKnobState)(nil),    // 12: modules.NeedyKnobState
	(*MazeState)(nil),         // 13: modules.MazeState
}
var file_proto_modules_proto_depIdxs = []int32{
	0,  // 0: modules.Module.type:type_name -> modules.Module.ModuleType
	1,  // 1: modules.Module.position:type_name -> modules.ModulePosition
	3,  // 2: modules.Module.wires_state:type_name -> modules.WiresState
	4,  // 3: modules.Module.password_state:type_name -> modules.PasswordState
	5,  // 4: modules.Module.big_button_state:type_name -> modules.BigButtonState
	6,  // 5: modules.Module.simon_state:type_name -> modules.SimonState
	7,  // 6: modules.Module.keypad_state:type_name -> modules.KeypadState
	8,  // 7: modules.Module.whos_on_first_state:type_name -> modules.WhosOnFirstState
	9,  // 8: modules.Module.memory_state:type_name -> modules.MemoryState
	10, // 9: modules.Module.morse_state:type_name -> modules.MorseState
	11, // 10: modules.Module.needy_vent_gas_state:type_name -> modules.NeedyVentGasState
	12, // 11: modules.Module.needy_knob_state:type_name -> modules.NeedyKnobState
	13, // 12: modules.Module.maze_state:type_name -> modules.MazeState
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_modules_proto_init() }
func file_proto_modules_proto_init() {
	if File_proto_modules_proto != nil {
		return
	}
	file_proto_wires_module_proto_init()
	file_proto_big_button_module_proto_init()
	file_proto_simon_module_proto_init()
	file_proto_password_module_proto_init()
	file_proto_keypad_module_proto_init()
	file_proto_whos_on_first_module_proto_init()
	file_proto_memory_module_proto_init()
	file_proto_morse_module_proto_init()
	file_proto_needy_vent_gas_module_proto_init()
	file_proto_needy_knob_module_proto_init()
	file_proto_maze_module_proto_init()
	file_proto_modules_proto_msgTypes[1].OneofWrappers = []any{
		(*Module_WiresState)(nil),
		(*Module_PasswordState)(nil),
		(*Module_BigButtonState)(nil),
		(*Module_SimonState)(nil),
		(*Module_KeypadState)(nil),
		(*Module_WhosOnFirstState)(nil),
		(*Module_MemoryState)(nil),
		(*Module_MorseState)(nil),
		(*Module_NeedyVentGasState)(nil),
		(*Module_NeedyKnobState)(nil),
		(*Module_MazeState)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_modules_proto_rawDesc), len(file_proto_modules_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_modules_proto_goTypes,
		DependencyIndexes: file_proto_modules_proto_depIdxs,
		EnumInfos:         file_proto_modules_proto_enumTypes,
		MessageInfos:      file_proto_modules_proto_msgTypes,
	}.Build()
	File_proto_modules_proto = out.File
	file_proto_modules_proto_goTypes = nil
	file_proto_modules_proto_depIdxs = nil
}
