// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/whos_on_first_module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WhosOnFirstInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhosOnFirstInput) Reset() {
	*x = WhosOnFirstInput{}
	mi := &file_proto_whos_on_first_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhosOnFirstInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhosOnFirstInput) ProtoMessage() {}

func (x *WhosOnFirstInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whos_on_first_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhosOnFirstInput.ProtoReflect.Descriptor instead.
func (*WhosOnFirstInput) Descriptor() ([]byte, []int) {
	return file_proto_whos_on_first_module_proto_rawDescGZIP(), []int{0}
}

func (x *WhosOnFirstInput) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type WhosOnFirstInputResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WhosOnFirstState *WhosOnFirstState      `protobuf:"bytes,1,opt,name=whos_on_first_state,json=whosOnFirstState,proto3" json:"whos_on_first_state,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WhosOnFirstInputResult) Reset() {
	*x = WhosOnFirstInputResult{}
	mi := &file_proto_whos_on_first_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhosOnFirstInputResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhosOnFirstInputResult) ProtoMessage() {}

func (x *WhosOnFirstInputResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whos_on_first_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhosOnFirstInputResult.ProtoReflect.Descriptor instead.
func (*WhosOnFirstInputResult) Descriptor() ([]byte, []int) {
	return file_proto_whos_on_first_module_proto_rawDescGZIP(), []int{1}
}

func (x *WhosOnFirstInputResult) GetWhosOnFirstState() *WhosOnFirstState {
	if x != nil {
		return x.WhosOnFirstState
	}
	return nil
}

type WhosOnFirstState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenWord    string                 `protobuf:"bytes,1,opt,name=screen_word,json=screenWord,proto3" json:"screen_word,omitempty"`
	ButtonWords   []string               `protobuf:"bytes,2,rep,name=button_words,json=buttonWords,proto3" json:"button_words,omitempty"`
	Stage         int32                  `protobuf:"varint,3,opt,name=stage,proto3" json:"stage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhosOnFirstState) Reset() {
	*x = WhosOnFirstState{}
	mi := &file_proto_whos_on_first_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhosOnFirstState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhosOnFirstState) ProtoMessage() {}

func (x *WhosOnFirstState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_whos_on_first_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhosOnFirstState.ProtoReflect.Descriptor instead.
func (*WhosOnFirstState) Descriptor() ([]byte, []int) {
	return file_proto_whos_on_first_module_proto_rawDescGZIP(), []int{2}
}

func (x *WhosOnFirstState) GetScreenWord() string {
	if x != nil {
		return x.ScreenWord
	}
	return ""
}

func (x *WhosOnFirstState) GetButtonWords() []string {
	if x != nil {
		return x.ButtonWords
	}
	return nil
}

func (x *WhosOnFirstState) GetStage() int32 {
	if x != nil {
		return x.Stage
	}
	return 0
}

var File_proto_whos_on_first_module_proto protoreflect.FileDescriptor

const file_proto_whos_on_first_module_proto_rawDesc = "" +
	"\n" +
	" proto/whos_on_first_module.proto\x12\amodules\x1a\x12proto/common.proto\"&\n" +
	"\x10WhosOnFirstInput\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"b\n" +
	"\x16WhosOnFirstInputResult\x12H\n" +
	"\x13whos_on_first_state\x18\x01 \x01(\v2\x19.modules.WhosOnFirstStateR\x10whosOnFirstState\"l\n" +
	"\x10WhosOnFirstState\x12\x1f\n" +
	"\vscreen_word\x18\x01 \x01(\tR\n" +
	"screenWord\x12!\n" +
	"\fbutton_words\x18\x02 \x03(\tR\vbuttonWords\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\x05R\x05stageB\tZ\a./protob\x06proto3"

var (
	file_proto_whos_on_first_module_proto_rawDescOnce sync.Once
	file_proto_whos_on_first_module_proto_rawDescData []byte
)

func file_proto_whos_on_first_module_proto_rawDescGZIP() []byte {
	file_proto_whos_on_first_module_proto_rawDescOnce.Do(func() {
		file_proto_whos_on_first_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_whos_on_first_module_proto_rawDesc), len(file_proto_whos_on_first_module_proto_rawDesc)))
	})
	return file_proto_whos_on_first_module_proto_rawDescData
}

var file_proto_whos_on_first_module_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_whos_on_first_module_proto_goTypes = []any{
	(*WhosOnFirstInput)(nil),       // 0: modules.WhosOnFirstInput
	(*WhosOnFirstInputResult)(nil), // 1: modules.WhosOnFirstInputResult
	(*WhosOnFirstState)(nil),       // 2: modules.WhosOnFirstState
}
var file_proto_whos_on_first_module_proto_depIdxs = []int32{
	2, // 0: modules.WhosOnFirstInputResult.whos_on_first_state:type_name -> modules.WhosOnFirstState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_whos_on_first_module_proto_init() }
func file_proto_whos_on_first_module_proto_init() {
	if File_proto_whos_on_first_module_proto != nil {
		return
	}
	file_proto_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_whos_on_first_module_proto_rawDesc), len(file_proto_whos_on_first_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_whos_on_first_module_proto_goTypes,
		DependencyIndexes: file_proto_whos_on_first_module_proto_depIdxs,
		MessageInfos:      file_proto_whos_on_first_module_proto_msgTypes,
	}.Build()
	File_proto_whos_on_first_module_proto = out.File
	file_proto_whos_on_first_module_proto_goTypes = nil
	file_proto_whos_on_first_module_proto_depIdxs = nil
}
