name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Tidy
        run: go mod tidy && git diff --exit-code

      - name: Format
        run: test -z "$(gofmt -l .)"

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1

      - name: Test
        run: go test ./... -v -race
